export const ABOUT_CONTENT = {
  en: {
    locale: 'en',
    hero: {
      homeHref: '/',
      breadcrumbHome: 'Home',
      breadcrumbCurrent: 'About',
      title: ['The Professional', 'Behind the Experience.'],
      tags: ['PGA Advanced Professional', 'Trackman Master Certified', 'TPI Level 3', 'Based in Mallorca'],
    },
    chapters: [
      {
        label: 'Early career',
        title: 'Following the best coaches across two continents.',
        paragraphs: [
          'I grew up playing golf, got down to a +1 handicap, but knew early that coaching was where I wanted to be. After studying Applied Golf Management at the University of Birmingham and qualifying as a PGA Professional, I started building a career following the most experienced coaches around Europe and North America.',
          "The early years took me to some remarkable venues. I coached at Pebble Beach, Doral, Evian during the women's major, and The Open Championship. I spent a season coaching aboard a cruise ship on a world voyage - over forty countries, golf in places most professionals never get near.",
        ],
        quote: 'Every environment was different. Every golfer was different. That variety, early on, is what shaped everything that came after.',
      },
      {
        label: 'Shanghai, 2014-2025',
        title: 'Eleven years at the top of the game in China.',
        paragraphs: [
          'In 2014 I moved to Shanghai. I went with specific goals - to set up the teaching programme for the best academy in China - and stayed for eleven successful years.',
          "China in that period was an extraordinary environment in which to coach. Lessons were running at around €500 per hour. Clients expected real, measurable improvement. That was the standard. The professional standard required was as high as anywhere I'd worked.",
          "I became the country's first Trackman Master, coached players from the Chinese national team, and built a coaching presence on Douyin that reached hundreds of millions of views. I also became fluent in Mandarin, which changed the depth of coaching relationship I could build with players and families.",
          "After eleven years, I'd achieved what I went for. My first daughter was born in 2023. The pull of being closer to home, and the chance to build something of my own, became impossible to ignore.",
        ],
      },
      {
        label: 'Mallorca, 2025-',
        title: 'Twenty-two courses, one island, and a coaching philosophy sharpened by playing again.',
        paragraphs: [
          "I moved to Mallorca in March 2025 with my wife Yina. Closer to family in the UK, year-round sunshine, and a genuinely exceptional golf island that most people don't give enough credit to.",
          'I started playing properly again. Working my way through every course on the island. Rediscovering what it feels like to stand on a first tee and actually care about the score. That competitive instinct, dormant through years of full-time coaching, came back fast.',
          "A PGA Professional who spent over a decade coaching in Asia, now hosting private golf days on one of Europe's best golf islands. If that sounds like the kind of day you're looking for, get in touch.",
        ],
        quote: "The coaching philosophy that's come out of playing again is simple: the fastest improvements happen on the course, not the range. Real conditions, real decisions. The progress that comes from that tends to stick.",
      },
    ],
    imageAlt: 'Andy Griffiths - UK PGA Advanced Professional, Mallorca',
    credentialsLabel: 'Credentials',
    credentials: [
      { title: 'UKPGA Advanced Professional', detail: 'Over 15,000 hours of coaching given' },
      { title: 'Applied Golf Management Studies', detail: 'University of Birmingham' },
      { title: 'TPI Level 3 Certified', detail: 'Titleist Performance Institute' },
      { title: 'Trackman Master Certified', detail: 'First in China' },
      { title: 'US Kids Golf', detail: 'Top 50 Coach Worldwide' },
      { title: '11 years in Shanghai', detail: 'Fluent Mandarin' },
      { title: 'Chinese National Team', detail: 'Elite junior and competition coaching' },
      { title: 'Hundreds of millions of views', detail: 'Golf coaching video content on Douyin' },
      { title: 'Published Author', detail: 'Putting It Out There - A Life in Full Swing, 2016 (Amazon)', isBookLink: true },
      { title: 'Based in Mallorca', detail: 'Since March 2025' },
    ],
    sidebarCta: {
      title: "Play Mallorca's finest courses with me alongside you.",
      body: 'Private days on Son Gual, Alcanada, and beyond. Everything arranged. On-course coaching throughout.',
      button: 'See the Experiences →',
      href: '/play-with-a-pro',
    },
    finalCta: {
      eyebrow: 'Ready to play?',
      title: 'A PGA Advanced Professional. An exceptional golf island. Your round.',
      body: "Tell me your dates, your handicap, and what you're looking for. I'll build the day around you.",
      primaryCta: 'See the Experiences →',
      primaryHref: '/play-with-a-pro',
      secondaryCta: 'Get in touch',
      secondaryHref: '/contact',
    },
  },
  de: {
    locale: 'de',
    hero: {
      homeHref: '/de',
      breadcrumbHome: 'Startseite',
      breadcrumbCurrent: 'Über',
      title: ['Der Profi', 'hinter dem Erlebnis.'],
      tags: ['PGA Advanced Professional', 'Trackman Master Zertifiziert', 'TPI Level 3', 'Auf Mallorca ansässig'],
    },
    chapters: [
      {
        label: 'Frühe Karriere',
        title: 'Den besten Trainern über zwei Kontinente folgen.',
        paragraphs: [
          'Ich bin mit Golf aufgewachsen, spielte mich bis auf Handicap +1 herunter und wusste früh, dass Coaching mein Weg sein würde. Nach meinem Studium im Applied Golf Management an der Universität Birmingham und meiner PGA-Qualifikation begann ich meine Karriere, indem ich den erfahrensten Trainern in Europa und Nordamerika folgte.',
          'Die frühen Jahre führten mich an bemerkenswerte Orte. Ich coachte in Pebble Beach, Doral, Evian während des Damen-Majors und bei The Open Championship. Eine Saison arbeitete ich auf einem Kreuzfahrtschiff während einer Weltreise - über vierzig Länder, Golf an Orten, die die meisten Professionals nie zu Gesicht bekommen.',
        ],
        quote: 'Jede Umgebung war anders. Jeder Golfer war anders. Diese Vielfalt in den frühen Jahren hat alles geprägt, was danach kam.',
      },
      {
        label: 'Shanghai, 2014-2025',
        title: 'Elf Jahre an der Spitze des Spiels in China.',
        paragraphs: [
          '2014 zog ich nach Shanghai. Ich ging mit einem klaren Ziel - das Trainingsprogramm für die beste Akademie Chinas aufzubauen - und blieb elf erfolgreiche Jahre.',
          'China war in dieser Zeit ein außergewöhnliches Umfeld für Coaching. Eine Stunde kostete rund 500 €. Kunden erwarteten echte, messbare Verbesserung. Das war der Standard. Der professionelle Anspruch war so hoch wie an jedem anderen Ort, an dem ich gearbeitet habe.',
          'Ich wurde Chinas erster Trackman Master, coachte Spieler des chinesischen Nationalteams und baute auf Douyin eine Coaching-Präsenz mit Hunderten Millionen Aufrufen auf. Außerdem wurde ich fließend in Mandarin, was die Tiefe der Beziehung zu Spielern und Familien deutlich verändert hat.',
          'Nach elf Jahren hatte ich erreicht, wofür ich gekommen war. Meine erste Tochter wurde 2023 geboren. Der Wunsch, wieder näher an der Heimat zu sein und etwas Eigenes aufzubauen, war nicht mehr zu ignorieren.',
        ],
      },
      {
        label: 'Mallorca, 2025-',
        title: 'Zweiundzwanzig Plätze, eine Insel und eine durch das eigene Spiel geschärfte Coaching-Philosophie.',
        paragraphs: [
          'Im März 2025 zog ich mit meiner Frau Yina nach Mallorca. Näher an der Familie im Vereinigten Königreich, ganzjähriger Sonnenschein und eine wirklich außergewöhnliche Golfinsel, die weit mehr Anerkennung verdient.',
          'Ich begann wieder ernsthaft zu spielen. Ich arbeite mich durch jeden Platz der Insel. Ich erinnere mich wieder daran, wie es sich anfühlt, am ersten Abschlag zu stehen und sich wirklich für das Ergebnis zu interessieren. Dieser Wettkampfinstinkt, der während Jahren im Vollzeit-Coaching geschlafen hatte, war schnell wieder da.',
          'Ein PGA Professional, der über ein Jahrzehnt in Asien gecoacht hat und jetzt private Golftage auf einer der besten Golfinseln Europas veranstaltet. Wenn das nach dem Tag klingt, den Sie suchen, dann melden Sie sich gern.',
        ],
        quote: 'Die Coaching-Philosophie, die daraus entstanden ist, wieder selbst zu spielen, ist einfach: Die schnellsten Verbesserungen passieren auf dem Platz, nicht auf der Range. Echte Bedingungen, echte Entscheidungen. Genau dieser Fortschritt bleibt.',
      },
    ],
    imageAlt: 'Andy Griffiths - UK PGA Advanced Professional, Mallorca',
    credentialsLabel: 'Qualifikationen',
    credentials: [
      { title: 'UKPGA Advanced Professional', detail: 'Über 15.000 Trainerstunden' },
      { title: 'Applied Golf Management Studies', detail: 'Universität Birmingham' },
      { title: 'TPI Level 3 Zertifiziert', detail: 'Titleist Performance Institute' },
      { title: 'Trackman Master Zertifiziert', detail: 'Erster in China' },
      { title: 'US Kids Golf', detail: 'Top 50 Coach weltweit' },
      { title: '11 Jahre in Shanghai', detail: 'Fließend Mandarin' },
      { title: 'Chinesisches Nationalteam', detail: 'Elite-Junioren- und Wettkampfcoaching' },
      { title: 'Hunderte Millionen Aufrufe', detail: 'Golf-Coaching-Videos auf Douyin' },
      { title: 'Veröffentlichter Autor', detail: 'Putting It Out There - A Life in Full Swing, 2016 (Amazon)', isBookLink: true },
      { title: 'Ansässig auf Mallorca', detail: 'Seit März 2025' },
    ],
    sidebarCta: {
      title: 'Spielen Sie Mallorcas beste Plätze mit mir an Ihrer Seite.',
      body: 'Private Tage auf Son Gual, Alcanada und darüber hinaus. Alles organisiert. On-course-Coaching während des gesamten Tages.',
      button: 'Die Erlebnisse ansehen →',
      href: '/de/play-with-a-pro',
    },
    finalCta: {
      eyebrow: 'Bereit zu spielen?',
      title: 'Ein PGA Advanced Professional. Eine außergewöhnliche Golfinsel. Ihre Runde.',
      body: 'Nennen Sie mir Ihre Daten, Ihr Handicap und wonach Sie suchen. Ich gestalte den Tag um Sie herum.',
      primaryCta: 'Die Erlebnisse ansehen →',
      primaryHref: '/de/play-with-a-pro',
      secondaryCta: 'Kontakt',
      secondaryHref: '/de/contact',
    },
  },
  es: {
    locale: 'es',
    hero: {
      homeHref: '/es',
      breadcrumbHome: 'Inicio',
      breadcrumbCurrent: 'Sobre Andy',
      title: ['El Profesional', 'detrás de la Experiencia.'],
      tags: ['UK PGA Advanced Professional', 'Trackman Master', 'TPI Level 3', 'Mallorca'],
    },
    chapters: [
      {
        label: 'Primeros años',
        title: 'Siguiendo a los mejores entrenadores en dos continentes.',
        paragraphs: [
          'Crecí jugando al golf, llegué a un hándicap de +1 y supe pronto que la enseñanza era mi camino. Tras estudiar Applied Golf Management en la Universidad de Birmingham y obtener la titulación de PGA Professional, empecé a construir mi carrera siguiendo a los entrenadores más experimentados de Europa y Norteamérica.',
          'Esos primeros años me llevaron a lugares extraordinarios. Entrené en Pebble Beach, Doral, Évian durante el major femenino y en The Open Championship. También pasé una temporada enseñando a bordo de un crucero en una vuelta al mundo - más de cuarenta países, golf en lugares a los que la mayoría de los profesionales nunca llega.',
        ],
        quote: 'Cada entorno era distinto. Cada golfista era distinto. Esa variedad, desde el principio, es lo que dio forma a todo lo que vino después.',
      },
      {
        label: 'Shanghái, 2014-2025',
        title: 'Once años en la cima del golf en China.',
        paragraphs: [
          'En 2014 me mudé a Shanghái. Fui con objetivos concretos - poner en marcha el programa de enseñanza de la mejor academia de China - y me quedé once años con grandes resultados.',
          'China, en ese periodo, fue un entorno extraordinario para enseñar. Las clases rondaban los 500 € por hora. Los clientes esperaban mejoras reales y medibles. Ese era el estándar. El nivel profesional exigido era tan alto como en cualquier otro lugar donde había trabajado.',
          'Me convertí en el primer Trackman Master del país, entrené a jugadores de la selección nacional china y construí una presencia de coaching en Douyin que alcanzó cientos de millones de visualizaciones. También llegué a hablar mandarín con fluidez, lo que cambió la profundidad de las relaciones que podía construir con jugadores y familias.',
          'Después de once años, había logrado lo que fui a hacer. Mi primera hija nació en 2023. El deseo de estar más cerca de casa y la oportunidad de construir algo propio se volvieron imposibles de ignorar.',
        ],
      },
      {
        label: 'Mallorca, 2025-',
        title: 'Veintidós campos, una isla y una filosofía de coaching afinada al volver a jugar.',
        paragraphs: [
          'Me mudé a Mallorca en marzo de 2025 con mi mujer Yina. Más cerca de la familia en el Reino Unido, sol todo el año y una isla de golf realmente excepcional a la que la mayoría de la gente no da suficiente crédito.',
          'Volví a jugar en serio. Recorriendo todos los campos de la isla. Redescubriendo lo que se siente al estar en el primer tee y realmente importarte el resultado. Ese instinto competitivo, dormido durante años de coaching a tiempo completo, volvió muy rápido.',
          'Un PGA Professional que pasó más de una década enseñando en Asia y que ahora organiza días privados de golf en una de las mejores islas de golf de Europa. Si eso suena como el tipo de día que está buscando, póngase en contacto.',
        ],
        quote: 'La filosofía de coaching que ha surgido de volver a jugar es sencilla: las mejoras más rápidas ocurren en el campo, no en la zona de prácticas. Condiciones reales, decisiones reales. Ese progreso suele quedarse.',
      },
    ],
    imageAlt: 'Andy Griffiths - profesional PGA en Mallorca',
    credentialsLabel: 'Credenciales',
    credentials: [
      { title: 'UKPGA Advanced Professional', detail: 'Más de 15.000 horas de coaching impartidas' },
      { title: 'Applied Golf Management Studies', detail: 'Universidad de Birmingham' },
      { title: 'Certificado TPI Nivel 3', detail: 'Titleist Performance Institute' },
      { title: 'Certificado Trackman Master', detail: 'Primero en China' },
      { title: 'US Kids Golf', detail: 'Top 50 Coach mundial' },
      { title: '11 años en Shanghái', detail: 'Mandarín fluido' },
      { title: 'Selección Nacional China', detail: 'Coaching de élite junior y competición' },
      { title: 'Cientos de millones de visualizaciones', detail: 'Contenido de coaching en Douyin' },
      { title: 'Autor publicado', detail: 'Putting It Out There - A Life in Full Swing, 2016 (Amazon)', isBookLink: true },
      { title: 'Residente en Mallorca', detail: 'Desde marzo de 2025' },
    ],
    sidebarCta: {
      title: 'Juegue los mejores campos de Mallorca conmigo a su lado.',
      body: 'Días privados en Son Gual, Alcanada y más. Todo organizado. Coaching en el campo durante todo el día.',
      button: 'Ver las experiencias →',
      href: '/es/play-with-a-pro',
    },
    careerStripProps: {
      label: 'Sedes y experiencia',
      heading: 'Donde se construyó la carrera.',
    },
    finalCta: {
      eyebrow: '¿Listo para jugar?',
      title: 'Un UK PGA Advanced Professional. Una isla de golf excepcional. Su vuelta.',
      body: 'Dígame sus fechas, su hándicap y lo que busca. Construiré el día en torno a usted.',
      primaryCta: 'Ver las experiencias →',
      primaryHref: '/es/play-with-a-pro',
      secondaryCta: 'Ponerse en contacto',
      secondaryHref: '/es/contact',
    },
  },
  fr: {
    locale: 'fr',
    hero: {
      homeHref: '/fr',
      breadcrumbHome: 'Accueil',
      breadcrumbCurrent: 'À propos',
      title: ['Le Professionnel', "Derrière l'Expérience."],
      tags: ['Professionnel PGA Avancé', 'Certifié Maître Trackman', 'TPI Niveau 3', 'Basé à Majorque'],
    },
    chapters: [
      {
        label: 'Débuts de carrière',
        title: 'Suivre les meilleurs coachs sur deux continents.',
        paragraphs: [
          "J'ai grandi avec le golf, je suis descendu à +1 de handicap et j'ai su très tôt que le coaching serait ma voie. Après des études d'Applied Golf Management à l'Université de Birmingham et ma qualification de professionnel PGA, j'ai commencé à construire ma carrière en suivant les coachs les plus expérimentés d'Europe et d'Amérique du Nord.",
          "Les premières années m'ont mené dans des lieux remarquables. J'ai coaché à Pebble Beach, Doral, Evian pendant le major féminin et à The Open Championship. J'ai aussi passé une saison à coacher à bord d'un paquebot pendant un tour du monde - plus de quarante pays, du golf dans des endroits que peu de professionnels approchent un jour.",
        ],
        quote: 'Chaque environnement était différent. Chaque golfeur était différent. Cette variété, au début, a façonné tout ce qui a suivi.',
      },
      {
        label: 'Shanghai, 2014-2025',
        title: 'Onze ans au sommet du golf en Chine.',
        paragraphs: [
          "En 2014, je me suis installé à Shanghai. J'y suis allé avec un objectif précis - mettre en place le programme d'enseignement de la meilleure académie de Chine - et j'y suis resté onze années réussies.",
          "La Chine, durant cette période, était un environnement extraordinaire pour coacher. Les leçons se facturaient autour de 500 € de l'heure. Les clients attendaient une amélioration réelle et mesurable. C'était la norme. Le niveau professionnel exigé était aussi élevé que partout ailleurs où j'avais travaillé.",
          "Je suis devenu le premier Trackman Master du pays, j'ai coaché des joueurs de l'équipe nationale chinoise et j'ai bâti une présence de coaching sur Douyin qui a atteint des centaines de millions de vues. Je suis aussi devenu courant en mandarin, ce qui a profondément changé la qualité des relations que je pouvais construire avec les joueurs et les familles.",
          "Après onze ans, j'avais accompli ce pour quoi j'étais venu. Ma première fille est née en 2023. Le désir de revenir plus près de chez moi et l'opportunité de construire quelque chose à moi sont devenus impossibles à ignorer.",
        ],
      },
      {
        label: 'Majorque, 2025-',
        title: 'Vingt-deux parcours, une île et une philosophie de coaching affûtée par le fait de rejouer.',
        paragraphs: [
          "Je me suis installé à Majorque en mars 2025 avec ma femme Yina. Plus près de ma famille au Royaume-Uni, du soleil toute l'année et une île de golf vraiment exceptionnelle à laquelle la plupart des gens ne rendent pas assez justice.",
          "J'ai recommencé à jouer sérieusement. En découvrant chaque parcours de l'île. En retrouvant cette sensation d'être sur le premier tee et de vraiment se soucier du score. Cet instinct compétitif, endormi pendant des années de coaching à plein temps, est revenu très vite.",
          "Un professionnel PGA qui a passé plus d'une décennie à coacher en Asie et qui organise désormais des journées de golf privées sur l'une des meilleures îles de golf d'Europe. Si cela ressemble au type de journée que vous recherchez, prenez contact.",
        ],
        quote: "La philosophie de coaching née du fait de rejouer est simple : les progrès les plus rapides se font sur le parcours, pas au practice. De vraies conditions, de vraies décisions. Les progrès obtenus ainsi ont tendance à durer.",
      },
    ],
    imageAlt: 'Andy Griffiths - Professionnel PGA avancé, Majorque',
    credentialsLabel: 'Références',
    credentials: [
      { title: 'Professionnel PGA Avancé', detail: 'Plus de 15 000 heures de coaching dispensées' },
      { title: 'Études en Gestion du Golf', detail: 'Université de Birmingham' },
      { title: 'Certifié TPI Niveau 3', detail: 'Titleist Performance Institute' },
      { title: 'Certifié Maître Trackman', detail: 'Premier en Chine' },
      { title: 'US Kids Golf', detail: 'Top 50 Coach mondial' },
      { title: '11 ans à Shanghai', detail: 'Mandarin courant' },
      { title: 'Équipe nationale chinoise', detail: 'Coaching élite junior et compétition' },
      { title: 'Des centaines de millions de vues', detail: 'Contenu vidéo de coaching sur Douyin' },
      { title: 'Auteur publié', detail: 'Putting It Out There - A Life in Full Swing, 2016 (Amazon)', isBookLink: true },
      { title: 'Basé à Majorque', detail: 'Depuis mars 2025' },
    ],
    sidebarCta: {
      title: 'Jouez les meilleurs parcours de Majorque à mes côtés.',
      body: 'Des journées privées à Son Gual, Alcanada et au-delà. Tout est organisé. Coaching sur le parcours tout au long de la journée.',
      button: 'Voir les expériences →',
      href: '/fr/play-with-a-pro',
    },
    finalCta: {
      eyebrow: 'Prêt à jouer ?',
      title: 'Un Professionnel PGA Avancé. Une île de golf exceptionnelle. Votre partie.',
      body: 'Dites-moi vos dates, votre handicap et ce que vous recherchez. Je construirai la journée autour de vous.',
      primaryCta: 'Voir les expériences →',
      primaryHref: '/fr/play-with-a-pro',
      secondaryCta: 'Nous contacter',
      secondaryHref: '/fr/contact',
    },
  },
  nl: {
    locale: 'nl',
    hero: { homeHref: '/nl', breadcrumbHome: 'Home', breadcrumbCurrent: 'Over Andy', title: ['De Professional', 'achter de Ervaring.'], tags: ['PGA Advanced Professional', 'Trackman Master gecertificeerd', 'TPI Niveau 3', 'Gevestigd op Mallorca'] },
    chapters: [
      { label: 'Vroege carrière', title: 'De beste coaches op twee continenten volgen.', paragraphs: ['Ik groeide op met golf, bereikte een handicap van +1 en wist al vroeg dat coaching mijn richting zou worden. Na mijn studie Applied Golf Management aan de University of Birmingham en mijn kwalificatie als PGA Professional begon ik een carrière op te bouwen door de meest ervaren coaches in Europa en Noord-Amerika te volgen.', 'Die vroege jaren brachten me naar bijzondere plekken. Ik coachte op Pebble Beach, Doral, Évian tijdens het dames-major en op The Open Championship. Ik bracht ook een seizoen door als coach op een cruiseschip tijdens een wereldreis - meer dan veertig landen, golf op plekken waar de meeste professionals nooit komen.'], quote: 'Elke omgeving was anders. Elke golfer was anders. Die variatie in de beginjaren heeft alles gevormd wat daarna kwam.' },
      { label: 'Shanghai, 2014-2025', title: 'Elf jaar aan de top van golf in China.', paragraphs: ['In 2014 verhuisde ik naar Shanghai. Ik ging met een helder doel - het lesprogramma opzetten voor de beste academie van China - en bleef elf succesvolle jaren.', 'China was in die periode een buitengewone omgeving om in te coachen. Lessen lagen rond de 500 € per uur. Klanten verwachtten echte, meetbare verbetering. Dat was de norm. De professionele standaard was net zo hoog als op elke andere plek waar ik had gewerkt.', 'Ik werd de eerste Trackman Master van het land, coachte spelers van het Chinese nationale team en bouwde op Douyin een coachingsaanwezigheid op die honderden miljoenen weergaven bereikte. Ik werd ook vloeiend in het Mandarijn, wat de diepte van de relatie met spelers en families sterk veranderde.', 'Na elf jaar had ik bereikt waarvoor ik gekomen was. Mijn eerste dochter werd geboren in 2023. De aantrekkingskracht van dichter bij huis zijn en de kans om iets van mezelf op te bouwen, waren niet langer te negeren.'] },
      { label: 'Mallorca, 2025-', title: 'Tweeëntwintig banen, één eiland en een coachingsfilosofie aangescherpt door zelf weer te spelen.', paragraphs: ['In maart 2025 verhuisde ik met mijn vrouw Yina naar Mallorca. Dichter bij familie in het VK, zon het hele jaar door en een werkelijk uitzonderlijk golfeiland dat de meeste mensen te weinig waarderen.', 'Ik begon weer serieus te spelen. Ik werk me door elke baan op het eiland heen. Ik ontdekte opnieuw hoe het voelt om op de eerste tee te staan en echt om de score te geven. Dat competitieve instinct, jarenlang slapend door fulltime coaching, kwam snel terug.', 'Een PGA Professional die meer dan tien jaar in Azië coachte en nu privé-golfdagen organiseert op een van de beste golfeilanden van Europa. Als dat klinkt als de dag die u zoekt, neem dan contact op.'], quote: 'De coachingsfilosofie die voortkwam uit weer spelen is eenvoudig: de snelste verbeteringen gebeuren op de baan, niet op de range. Echte omstandigheden, echte beslissingen. Vooruitgang die zo ontstaat, blijft hangen.' },
    ],
    imageAlt: 'Andy Griffiths - UK PGA Advanced Professional, Mallorca',
    credentialsLabel: 'Kwalificaties',
    credentials: [{ title: 'UKPGA Advanced Professional', detail: 'Meer dan 15.000 uur coaching gegeven' }, { title: 'Applied Golf Management Studies', detail: 'University of Birmingham' }, { title: 'TPI Niveau 3 gecertificeerd', detail: 'Titleist Performance Institute' }, { title: 'Trackman Master gecertificeerd', detail: 'Eerste in China' }, { title: 'US Kids Golf', detail: 'Top 50 Coach wereldwijd' }, { title: '11 jaar in Shanghai', detail: 'Vloeiend Mandarijn' }, { title: 'Chinees Nationaal Team', detail: 'Elite junior- en wedstrijdcoaching' }, { title: 'Honderden miljoenen weergaven', detail: 'Golfcoaching-video’s op Douyin' }, { title: 'Gepubliceerd auteur', detail: 'Putting It Out There - A Life in Full Swing, 2016 (Amazon)', isBookLink: true }, { title: 'Gevestigd op Mallorca', detail: 'Sinds maart 2025' }],
    sidebarCta: { title: 'Speel de mooiste banen van Mallorca met mij aan uw zijde.', body: 'Privédagen op Son Gual, Alcanada en meer. Alles geregeld. Coaching op de baan gedurende de hele dag.', button: 'Bekijk de ervaringen →', href: '/nl/play-with-a-pro' },
    finalCta: { eyebrow: 'Klaar om te spelen?', title: 'Een PGA Advanced Professional. Een uitzonderlijk golfeiland. Uw ronde.', body: 'Vertel me uw data, uw handicap en wat u zoekt. Ik bouw de dag rondom u.', primaryCta: 'Bekijk de ervaringen →', primaryHref: '/nl/play-with-a-pro', secondaryCta: 'Neem contact op', secondaryHref: '/nl/contact' },
  },
  sv: {
    locale: 'sv',
    hero: { homeHref: '/sv', breadcrumbHome: 'Hem', breadcrumbCurrent: 'Om', title: ['Professionellen', 'bakom upplevelsen.'], tags: ['PGA Advanced Professional', 'Trackman Master Certified', 'TPI Level 3', 'Baserad i Mallorca'] },
    chapters: [
      { label: 'Tidigt i karriären', title: 'Följde de bästa tränarna över två kontinenter.', paragraphs: ['Jag växte upp med golf, nådde +1 i handicap och visste tidigt att coaching var min väg. Efter studier i Applied Golf Management vid University of Birmingham och min kvalificering som PGA Professional började jag bygga en karriär genom att följa de mest erfarna tränarna runt om i Europa och Nordamerika.', 'De tidiga åren tog mig till några anmärkningsvärda platser. Jag coachade på Pebble Beach, Doral, Evian under damernas major och vid The Open Championship. Jag tillbringade även en säsong med att coacha ombord på ett kryssningsfartyg under en världsomsegling - över fyrtio länder, golf på platser som de flesta proffs aldrig kommer nära.'], quote: 'Varje miljö var annorlunda. Varje golfare var annorlunda. Den variationen tidigt i karriären formade allt som kom efteråt.' },
      { label: 'Shanghai, 2014-2025', title: 'Elva år på toppen av golfen i Kina.', paragraphs: ['2014 flyttade jag till Shanghai. Jag kom dit med ett tydligt mål - att bygga upp undervisningsprogrammet för den bästa akademin i Kina - och stannade i elva framgångsrika år.', 'Kina under den perioden var en extraordinär miljö för coaching. Lektioner låg på omkring 500 € i timmen. Kunder förväntade sig verklig, mätbar förbättring. Det var standarden. Den professionella nivå som krävdes var lika hög som någon annanstans där jag hade arbetat.', 'Jag blev landets första Trackman Master, coachade spelare från Kinas landslag och byggde upp en coachingnärvaro på Douyin som nådde hundratals miljoner visningar. Jag blev också flytande i mandarin, vilket förändrade djupet i relationerna jag kunde skapa med spelare och familjer.', 'Efter elva år hade jag uppnått det jag kom för. Min första dotter föddes 2023. Dragningen att komma närmare hemmet och möjligheten att bygga något eget blev omöjlig att ignorera.'] },
      { label: 'Mallorca, 2025-', title: 'Tjugotvå banor, en ö och en coachingfilosofi skärpt genom att spela igen.', paragraphs: ['Jag flyttade till Mallorca i mars 2025 med min fru Yina. Närmare familjen i Storbritannien, solsken året runt och en verkligt exceptionell golfö som de flesta inte ger tillräckligt erkännande.', 'Jag började spela ordentligt igen. Jag arbetade mig genom varje bana på ön. Jag återupptäckte hur det känns att stå på första tee och faktiskt bry sig om resultatet. Den tävlingsinstinkt som varit vilande under år av heltidscoaching kom snabbt tillbaka.', 'En PGA Professional som tillbringade mer än ett decennium med att coacha i Asien och som nu arrangerar privata golfdagar på en av Europas bästa golföar. Om det låter som den typ av dag du letar efter, hör av dig.'], quote: 'Coachingfilosofin som kom ur att spela igen är enkel: de snabbaste förbättringarna sker på banan, inte på rangen. Verkliga förhållanden, verkliga beslut. Framsteg som skapas där brukar stanna kvar.' },
    ],
    imageAlt: 'Andy Griffiths - UK PGA Advanced Professional, Mallorca',
    credentialsLabel: 'Meriter',
    credentials: [{ title: 'UKPGA Advanced Professional', detail: 'Över 15 000 timmars coaching' }, { title: 'Applied Golf Management Studies', detail: 'University of Birmingham' }, { title: 'TPI Level 3 Certified', detail: 'Titleist Performance Institute' }, { title: 'Trackman Master Certified', detail: 'Först i Kina' }, { title: 'US Kids Golf', detail: 'Top 50 Coach Worldwide' }, { title: '11 år i Shanghai', detail: 'Flytande mandarin' }, { title: 'Chinese National Team', detail: 'Elitcoachning för juniorer och tävling' }, { title: 'Hundratals miljoner visningar', detail: 'Golfcoaching-videor på Douyin' }, { title: 'Published Author', detail: 'Putting It Out There - A Life in Full Swing, 2016 (Amazon)', isBookLink: true }, { title: 'Baserad i Mallorca', detail: 'Sedan mars 2025' }],
    sidebarCta: { title: 'Spela Mallorcas finaste banor med mig vid din sida.', body: 'Privata dagar på Son Gual, Alcanada och fler därtill. Allt ordnat. Coaching ute på banan hela dagen.', button: 'Se upplevelserna →', href: '/sv/play-with-a-pro' },
    finalCta: { eyebrow: 'Redo att spela?', title: 'En PGA Advanced Professional. En exceptionell golfö. Din runda.', body: 'Berätta dina datum, ditt handicap och vad du letar efter. Jag bygger dagen runt dig.', primaryCta: 'Se upplevelserna →', primaryHref: '/sv/play-with-a-pro', secondaryCta: 'Kontakta mig', secondaryHref: '/sv/contact' },
  },
  zh: {
    locale: 'zh',
    hero: { homeHref: '/zh', breadcrumbHome: '首页', breadcrumbCurrent: '关于', title: ['体验背后', '的专业人士。'], tags: ['PGA高级职业教练', 'Trackman大师认证', 'TPI 3级', '现居马略卡'] },
    chapters: [
      { label: '职业早期', title: '追随两大洲最优秀的教练。', paragraphs: ['我从小打高尔夫，最低打到过 +1 差点，但很早就知道，教学才是我真正想走的路。在伯明翰大学学习应用高尔夫管理并取得 PGA Professional 资格后，我开始在欧洲和北美追随最有经验的教练，逐步建立自己的职业生涯。', '职业早期把我带到了很多特别的地方。我曾在 Pebble Beach、Doral、Evian 女子大满贯以及 The Open Championship 期间执教。我还在一艘邮轮上执教了一个赛季，完成了环球航行 - 超过四十个国家，在很多职业球员一辈子都不会接触到的地方打高尔夫。'], quote: '每一个环境都不同。每一个球员都不同。正是这种早期的多样性，塑造了后来的一切。' },
      { label: '上海，2014-2025', title: '在中国顶级教学环境中的十一年。', paragraphs: ['2014 年我搬到了上海。我带着明确的目标而去 - 为中国最好的高尔夫学院建立教学项目 - 并在那里度过了成功的十一年。', '那段时间的中国，是一个非常特殊的执教环境。课程收费大约为每小时 500 欧元。客户期待真实、可衡量的提升。这就是标准。所要求的职业水准，与我在任何地方工作时一样高。', '我成为中国第一位 Trackman Master，执教过中国国家队球员，并在抖音上建立起拥有数亿播放量的高尔夫教学影响力。我也变得能够流利使用普通话，这改变了我与球员及其家庭建立关系的深度。', '十一年之后，我已经完成了自己当初想做的事。我的大女儿在 2023 年出生。更靠近家人、并建立属于自己的事业，这种吸引力已经无法忽视。'] },
      { label: '马略卡，2025-', title: '二十二座球场，一座岛屿，以及在重新认真打球后被磨砺出的教学理念。', paragraphs: ['2025 年 3 月，我和妻子 Yina 搬到了马略卡。这里离英国的家人更近，全年阳光充足，而且是一座真正出色、却常常被低估的高尔夫岛屿。', '我也重新开始认真打球，走遍岛上的每一座球场。重新找回站在第一洞发球台上、真正关心成绩的感觉。那个在多年全职教学中沉睡下来的竞争本能，很快就回来了。', '一位在亚洲执教超过十年的 PGA Professional，如今在欧洲最好的高尔夫岛屿之一举办私人高尔夫日。如果这听起来正是你想要的一天，欢迎联系我。'], quote: '重新开始认真打球后，我的教学理念变得很简单：最快的进步发生在球场上，而不是练习场。真实条件，真实决策。这样得到的进步，往往更能保持。' },
    ],
    imageAlt: 'Andy Griffiths - 英国 PGA 高级职业教练，马略卡',
    credentialsLabel: '资历',
    credentials: [{ title: '英国PGA高级职业教练', detail: '累计执教超过 15,000 小时' }, { title: '应用高尔夫管理研究', detail: '伯明翰大学' }, { title: 'TPI 3级认证', detail: 'Titleist Performance Institute' }, { title: 'Trackman大师认证', detail: '中国首位' }, { title: 'US Kids Golf 认证', detail: '全球前 50 教练' }, { title: '上海 11 年', detail: '普通话流利' }, { title: '中国国家队', detail: '精英青少年与竞赛教学' }, { title: '数亿次观看', detail: '抖音高尔夫教学视频内容' }, { title: '出版作者', detail: 'Putting It Out There - A Life in Full Swing, 2016 (Amazon)', isBookLink: true }, { title: '现居马略卡', detail: '自 2025 年 3 月起' }],
    sidebarCta: { title: '与我一起打马略卡最好的球场。', body: '在 Son Gual、Alcanada 以及更多球场安排私人高尔夫日。全程安排妥当，并提供球场实战教学。', button: '查看体验 →', href: '/zh/play-with-a-pro' },
    finalCta: { eyebrow: '准备好下场了吗？', title: 'PGA高级职业教练。一座非凡的高尔夫岛屿。属于你的一轮。', body: '告诉我你的日期、差点和你想要的体验。我会围绕你来安排这一天。', primaryCta: '查看体验 →', primaryHref: '/zh/play-with-a-pro', secondaryCta: '联系我', secondaryHref: '/zh/contact' },
  },
}

export function getAboutContent(locale = 'en') {
  return ABOUT_CONTENT[locale] || ABOUT_CONTENT.en
}
