export const COACHING_CONTENT = {
  en: {
    locale: 'en',
    imageAlt: 'Andy Griffiths coaching golf on a Mallorca course',
    hero: {
      breadcrumbHome: 'Home',
      breadcrumbCurrent: 'On-Course Coaching',
      title: 'Better Golf. Without Changing Everything.',
      body: "On-course coaching for visiting and resident golfers. Real conditions, real decisions, real improvement - without the technical overload that disappears by the 3rd hole.",
    },
    range: {
      eyebrow: "Why the range isn't enough",
      title: "There's a reason your range game doesn't show up on the course.",
      paragraphs: [
        'The range is flat, controlled, and consequence-free. Then you stand on the 1st tee and none of it transfers.',
        "On-course coaching puts the lesson where it actually matters: on the fairway, in the rough, in the wind, with a score that matters.",
      ],
      quote: 'Think of it like boxing. The first tee is not the driving range.',
      quoteAttribution: 'Andy Griffiths, PGA Advanced Professional',
      questionnaireEyebrow: 'The questionnaire',
      questionnaireParagraphs: [
        "A short questionnaire shapes the day before we start: what's frustrating you, where the gaps are, and what success looks like.",
        'By the first tee, I already know what to look for. The feedback is situational and honest, not generic.',
        'Sessions take place at Son Gual, Alcanada, or a course matched to your level and goals.',
      ],
      questionnaireCta: 'Discuss a Session →',
    },
    improvements: {
      eyebrow: 'What actually gets better',
      title: "Here's what changes during a round with me.",
      sub: 'And why it sticks in a way range work rarely does.',
      items: [
        { num: '01', title: 'Course management', text: 'Most golfers lose more shots to poor decisions than poor swings. Club, target, shape - these choices separate a 90 from an 80.' },
        { num: '02', title: 'Shot selection under pressure', text: 'The decisions that fall apart under pressure become visible on the course in a way they never do on a range.' },
        { num: '03', title: 'Reading greens and slopes', text: 'Putting and chipping on a real green is completely different from a practice green. Speed, slope, grain, and pressure all matter.' },
        { num: '04', title: 'Playing in wind', text: 'Mallorca is windy. Son Gual especially has its own wind ecosystem. This only gets trained when it is actually blowing.' },
        { num: '05', title: 'Mental game and routine', text: 'How you speak to yourself, how you reset, and whether your routine holds up under pressure only shows up when the consequences are real.' },
        { num: '06', title: 'Finding the low-hanging fruit', text: 'Most golfers improve fastest through one or two small unlocks, not a total rebuild. Real-world lies, fairways, and rough show you what matters.' },
      ],
    },
    how: {
      eyebrow: 'How it works',
      title: 'Three stages. One session that changes how you play.',
      body: 'We play together on-course. The coaching happens in real time, and the feedback is practical, honest, and specific to what is happening in front of us.',
      steps: [
        { num: '01', title: 'The questionnaire', text: 'You complete a short form before the session so I already have a picture by the first tee.' },
        { num: '02', title: 'The round', text: 'We play together. The right observation arrives at the right moment - not as a lecture, but as something that changes your score.' },
        { num: '03', title: 'The debrief', text: 'Over lunch, we cover what improved, what to work on, and what to take away.' },
      ],
    },
    who: {
      eyebrow: 'Who this is for',
      title: 'If any of these sound familiar, this is for you.',
      cards: [
        { title: 'Visiting golfers', text: 'Focused improvement during your time on the island.' },
        { title: 'Resident golfers', text: 'Regular work with a professional who knows the same courses you play.' },
        { title: 'The range/course gap', text: 'Your practice game never transfers.' },
        { title: 'Smarter, not rebuilt', text: 'You want to play better without rebuilding everything from scratch.' },
      ],
    },
    finalCta: {
      eyebrow: 'Ready to play better?',
      title: 'Get in touch to discuss a session.',
      body: "Tell me where your game is and what you want from it. I'll build the session around that.",
      primaryCta: 'Get in Touch →',
      secondaryCta: 'See Full Experiences',
    },
  },
  de: {
    locale: 'de',
    imageAlt: 'Andy Griffiths coacht Golf auf Mallorca',
    hero: { breadcrumbHome: 'Startseite', breadcrumbCurrent: 'On-Course Coaching', title: 'Besser Golf. Ohne alles zu aendern.', body: 'On-Course Coaching fuer besuchende und ansaessige Golfer. Echte Bedingungen, echte Entscheidungen und echte Verbesserung - ohne technische Ueberladung.' },
    range: {
      eyebrow: 'Warum die Range nicht reicht',
      title: 'Es gibt einen Grund, warum sich Ihr Range-Spiel nicht auf den Platz uebertraegt.',
      paragraphs: ['Die Range ist flach, kontrolliert und ohne echte Konsequenzen. Am 1. Abschlag zeigt sich, was wirklich uebertragbar ist.', 'On-Course Coaching setzt die Lektion dorthin, wo sie hilft: aufs Fairway, ins Rough, in den Wind und in Situationen mit echtem Score.'],
      quote: 'Der 1. Abschlag ist nicht die Driving Range.',
      quoteAttribution: 'Andy Griffiths, PGA Advanced Professional',
      questionnaireEyebrow: 'Der Fragebogen',
      questionnaireParagraphs: ['Ein kurzer Fragebogen formt den Tag, bevor wir starten.', 'Am 1. Abschlag weiss ich bereits, worauf ich achten muss.', 'Sessions finden in Son Gual, Alcanada oder auf einem passenden Platz statt.'],
      questionnaireCta: 'Session besprechen →',
    },
    improvements: {
      eyebrow: 'Was sich wirklich verbessert',
      title: 'Das veraendert sich waehrend einer Runde mit mir.',
      sub: 'Und warum es haften bleibt.',
      items: [
        { num: '01', title: 'Platzmanagement', text: 'Die meisten Schlaege gehen durch falsche Entscheidungen verloren, nicht durch den falschen Schwung.' },
        { num: '02', title: 'Schlagauswahl unter Druck', text: 'Unter Druck werden Entscheidungen sichtbar, die auf der Range verborgen bleiben.' },
        { num: '03', title: 'Gruens und Haenge lesen', text: 'Tempo, Hang und Korn veraendern auf echten Gruens alles.' },
        { num: '04', title: 'Im Wind spielen', text: 'Seitenwind, Flugbahn und Vertrauen lassen sich nur im echten Wind trainieren.' },
        { num: '05', title: 'Mentales Spiel und Routine', text: 'Wie Sie nach einem schlechten Schlag reagieren, zeigt sich nur mit echten Konsequenzen.' },
        { num: '06', title: 'Die schnellsten Hebel finden', text: 'Kleine Entdeckungen bringen oft mehr als ein kompletter Umbau - gerade auf echten Lies und engen Fairways.' },
      ],
    },
    how: {
      eyebrow: 'So funktioniert es',
      title: 'Drei Phasen. Eine Session, die veraendert, wie Sie spielen.',
      body: 'Wir spielen gemeinsam auf dem Platz. Das Coaching ist situativ, ehrlich und direkt nutzbar.',
      steps: [
        { num: '01', title: 'Der Fragebogen', text: 'Vor der Session fuellen Sie ein kurzes Formular aus.' },
        { num: '02', title: 'Die Runde', text: 'Die richtige Beobachtung kommt im richtigen Moment.' },
        { num: '03', title: 'Die Nachbesprechung', text: 'Beim Mittagessen sprechen wir ueber das, was Sie mitnehmen koennen.' },
      ],
    },
    who: {
      eyebrow: 'Fuer wen das gedacht ist',
      title: 'Wenn Ihnen etwas davon bekannt vorkommt, ist das fuer Sie.',
      cards: [
        { title: 'Besuchende Golfer', text: 'Gezielte Verbesserung waehrend Ihrer Zeit auf der Insel.' },
        { title: 'Ansaessige Golfer', text: 'Regelmaessige Arbeit mit einem Professional, der die gleichen Plaetze kennt.' },
        { title: 'Die Luecke zwischen Range und Platz', text: 'Ihr Uebungsspiel uebertraegt sich nie.' },
        { title: 'Klueger statt komplett neu', text: 'Sie wollen besser spielen, ohne alles von Grund auf neu zu bauen.' },
      ],
    },
    finalCta: { eyebrow: 'Bereit, besser zu spielen?', title: 'Kontaktieren Sie mich, um eine Session zu besprechen.', body: 'Sagen Sie mir, wo Ihr Spiel steht und was Sie erreichen moechten.', primaryCta: 'Kontakt aufnehmen →', secondaryCta: 'Alle Experiences ansehen' },
  },
  es: {
    locale: 'es',
    imageAlt: 'Andy Griffiths dando coaching de golf en Mallorca',
    hero: { breadcrumbHome: 'Inicio', breadcrumbCurrent: 'Coaching en campo', title: 'Mejor golf. Sin cambiarlo todo.', body: 'Coaching en campo para golfistas de visita y residentes. Condiciones reales, decisiones reales y mejora real, sin la sobrecarga tecnica.' },
    range: {
      eyebrow: 'Por que la zona de practica no basta',
      title: 'Hay una razon por la que su juego de practica no aparece en el campo.',
      paragraphs: ['La zona de practica es plana, controlada y sin consecuencias. El campo muestra lo que de verdad se transfiere.', 'El coaching en campo coloca la leccion donde realmente ayuda: en la calle, en el rough, en el viento y con un resultado en juego.'],
      quote: 'El primer tee no es la zona de practica.',
      quoteAttribution: 'Andy Griffiths, PGA Advanced Professional',
      questionnaireEyebrow: 'El cuestionario',
      questionnaireParagraphs: ['Un breve cuestionario da forma al dia antes de empezar.', 'Cuando llegamos al primer tee, ya se que debo observar.', 'Las sesiones tienen lugar en Son Gual, Alcanada o un campo adaptado a usted.'],
      questionnaireCta: 'Hablar de una sesion →',
    },
    improvements: {
      eyebrow: 'Lo que realmente mejora',
      title: 'Esto es lo que cambia durante una vuelta conmigo.',
      sub: 'Y por que se mantiene.',
      items: [
        { num: '01', title: 'Gestion del campo', text: 'La mayoria pierde golpes por malas decisiones, no por el swing.' },
        { num: '02', title: 'Eleccion de golpe bajo presion', text: 'Las decisiones bajo presion se vuelven visibles en el campo.' },
        { num: '03', title: 'Leer greens y pendientes', text: 'Velocidad, pendiente y grano cambian lo que funciona.' },
        { num: '04', title: 'Jugar con viento', text: 'El viento real de Mallorca exige elecciones y trayectorias reales.' },
        { num: '05', title: 'Juego mental y rutina', text: 'La parte mental solo aparece cuando las consecuencias son reales.' },
        { num: '06', title: 'Encontrar las mejoras rapidas', text: 'Uno o dos pequenos cambios suelen aportar mas que una reconstruccion completa.' },
      ],
    },
    how: {
      eyebrow: 'Como funciona',
      title: 'Tres fases. Una sesion que cambia como juega.',
      body: 'Jugamos juntos en el campo. El coaching ocurre en tiempo real y el feedback es directo y util.',
      steps: [
        { num: '01', title: 'El cuestionario', text: 'Antes de la sesion completa un breve formulario.' },
        { num: '02', title: 'La vuelta', text: 'La observacion adecuada llega en el momento adecuado.' },
        { num: '03', title: 'La puesta en comun', text: 'Durante la comida repasamos que mejora y que debe llevarse.' },
      ],
    },
    who: {
      eyebrow: 'Para quien es esto',
      title: 'Si algo de esto le suena, esto es para usted.',
      cards: [
        { title: 'Golfistas de visita', text: 'Mejora enfocada durante su estancia en la isla.' },
        { title: 'Golfistas residentes', text: 'Trabajo regular con un profesional que conoce los mismos campos.' },
        { title: 'La brecha practica-campo', text: 'Su juego de practica nunca se traslada al campo.' },
        { title: 'Mas inteligente, no reconstruido', text: 'Quiere jugar mejor sin empezar de cero.' },
      ],
    },
    finalCta: { eyebrow: 'Listo para jugar mejor?', title: 'Contacteme para hablar de una sesion.', body: 'Digame donde esta su juego y que quiere conseguir.', primaryCta: 'Ponerse en contacto →', secondaryCta: 'Ver experiencias completas' },
  },
  fr: {
    locale: 'fr',
    imageAlt: 'Andy Griffiths donnant un coaching de golf a Majorque',
    hero: { breadcrumbHome: 'Accueil', breadcrumbCurrent: 'Coaching sur parcours', title: 'Un meilleur golf. Sans tout changer.', body: 'Coaching sur parcours pour les golfeurs en visite et les residents. Conditions reelles, decisions reelles et progression reelle, sans surcharge technique.' },
    range: {
      eyebrow: 'Pourquoi le practice ne suffit pas',
      title: 'Il y a une raison pour laquelle votre jeu de practice ne se retrouve pas sur le parcours.',
      paragraphs: ['Le practice est plat, controle et sans consequence. Le parcours montre ce qui se transfere vraiment.', 'Le coaching sur parcours place la lecon la ou elle aide vraiment: sur le fairway, dans le rough, dans le vent et avec un score qui compte.'],
      quote: 'Le premier tee n est pas le practice.',
      quoteAttribution: 'Andy Griffiths, PGA Advanced Professional',
      questionnaireEyebrow: 'Le questionnaire',
      questionnaireParagraphs: ['Un court questionnaire donne de la forme a la journee avant de commencer.', 'Au premier tee, je sais deja ce que je dois observer.', 'Les sessions ont lieu a Son Gual, Alcanada ou sur un parcours adapte.'],
      questionnaireCta: 'Discuter d une session →',
    },
    improvements: {
      eyebrow: 'Ce qui s ameliore vraiment',
      title: 'Voici ce qui change pendant un tour avec moi.',
      sub: 'Et pourquoi cela tient.',
      items: [
        { num: '01', title: 'Gestion du parcours', text: 'La plupart des coups perdus viennent de mauvaises decisions plus que d un mauvais swing.' },
        { num: '02', title: 'Choix de coups sous pression', text: 'Sous pression, les mauvaises decisions deviennent visibles sur le parcours.' },
        { num: '03', title: 'Lecture des greens et des pentes', text: 'La vitesse, la pente et le grain changent ce qui fonctionne.' },
        { num: '04', title: 'Jouer dans le vent', text: 'Le vrai vent de Majorque oblige a prendre de vraies decisions de trajectoire.' },
        { num: '05', title: 'Mental et routine', text: 'Le mental n apparait vraiment que lorsque les consequences sont reelles.' },
        { num: '06', title: 'Trouver les gains rapides', text: 'Un ou deux petits debloquages apportent souvent plus qu une reconstruction complete.' },
      ],
    },
    how: {
      eyebrow: 'Comment cela fonctionne',
      title: 'Trois etapes. Une session qui change votre facon de jouer.',
      body: 'Nous jouons ensemble sur le parcours. Le coaching arrive au bon moment et le retour est concret et honnete.',
      steps: [
        { num: '01', title: 'Le questionnaire', text: 'Avant la session, vous remplissez un court formulaire.' },
        { num: '02', title: 'Le tour', text: 'L observation juste arrive au moment ou elle compte.' },
        { num: '03', title: 'Le debrief', text: 'Au dejeuner, nous clarifions ce qui a progresse et ce qu il faut garder.' },
      ],
    },
    who: {
      eyebrow: 'Pour qui est-ce',
      title: 'Si cela vous parle, c est probablement pour vous.',
      cards: [
        { title: 'Golfeurs en visite', text: 'Une progression ciblee pendant votre sejour sur l ile.' },
        { title: 'Golfeurs residents', text: 'Un travail regulier avec un professionnel qui connait les memes parcours.' },
        { title: 'L ecart practice-parcours', text: 'Votre jeu d entrainement ne se transfere jamais.' },
        { title: 'Mieux jouer, sans tout reconstruire', text: 'Vous voulez mieux jouer sans repartir de zero.' },
      ],
    },
    finalCta: { eyebrow: 'Pret a mieux jouer ?', title: 'Contactez-moi pour discuter d une session.', body: 'Dites-moi ou en est votre jeu et ce que vous voulez en tirer.', primaryCta: 'Prendre contact →', secondaryCta: 'Voir les experiences completes' },
  },
  nl: {
    locale: 'nl',
    imageAlt: 'Andy Griffiths geeft golfcoaching op Mallorca',
    hero: { breadcrumbHome: 'Home', breadcrumbCurrent: 'On-Course Coaching', title: 'Beter golf. Zonder alles te veranderen.', body: 'On-course coaching voor bezoekers en residenten. Echte omstandigheden, echte beslissingen en echte verbetering, zonder technische overbelasting.' },
    range: {
      eyebrow: 'Waarom de driving range niet genoeg is',
      title: 'Er is een reden waarom uw range-spel niet op de baan verschijnt.',
      paragraphs: ['De range is vlak, gecontroleerd en zonder echte gevolgen. Op de baan blijkt wat echt standhoudt.', 'On-course coaching zet de les waar die helpt: op de fairway, in het rough, in de wind en onder echte score-druk.'],
      quote: 'De eerste tee is niet de driving range.',
      quoteAttribution: 'Andy Griffiths, PGA Advanced Professional',
      questionnaireEyebrow: 'De vragenlijst',
      questionnaireParagraphs: ['Een korte vragenlijst vormt de dag nog voor we beginnen.', 'Bij de eerste tee weet ik al waar ik op moet letten.', 'Sessies vinden plaats op Son Gual, Alcanada of een passende baan.'],
      questionnaireCta: 'Bespreek een sessie →',
    },
    improvements: {
      eyebrow: 'Wat echt beter wordt',
      title: 'Dit verandert tijdens een ronde met mij.',
      sub: 'En daarom blijft het hangen.',
      items: [
        { num: '01', title: 'Baanmanagement', text: 'De meeste slagen gaan verloren door verkeerde beslissingen, niet door de swing.' },
        { num: '02', title: 'Shotkeuze onder druk', text: 'Beslissingen onder druk worden op de baan zichtbaar.' },
        { num: '03', title: 'Greens en hellingen lezen', text: 'Snelheid, helling en grain veranderen wat werkt.' },
        { num: '04', title: 'Spelen in de wind', text: 'De echte Mallorcaanse wind dwingt tot echte keuzes.' },
        { num: '05', title: 'Mentaal spel en routine', text: 'Het mentale deel verschijnt pas echt wanneer de gevolgen voelbaar zijn.' },
        { num: '06', title: 'De snelste winst vinden', text: 'Een of twee kleine unlocks brengen vaak meer dan een totale rebuild.' },
      ],
    },
    how: {
      eyebrow: 'Hoe het werkt',
      title: 'Drie fases. Een sessie die verandert hoe u speelt.',
      body: 'We spelen samen op de baan. De coaching gebeurt op het juiste moment en de feedback is praktisch en eerlijk.',
      steps: [
        { num: '01', title: 'De vragenlijst', text: 'Voor de sessie vult u een korte vragenlijst in.' },
        { num: '02', title: 'De ronde', text: 'De juiste observatie komt precies op het moment dat het telt.' },
        { num: '03', title: 'De nabespreking', text: 'Tijdens de lunch maken we helder wat beter ging en wat u moet meenemen.' },
      ],
    },
    who: {
      eyebrow: 'Voor wie dit is',
      title: 'Als iets hiervan herkenbaar klinkt, is dit voor u.',
      cards: [
        { title: 'Bezoekende golfers', text: 'Gerichte verbetering tijdens uw tijd op het eiland.' },
        { title: 'Resident golfers', text: 'Regelmatig werk met een professional die dezelfde banen kent.' },
        { title: 'De range-baan kloof', text: 'Uw oefenspel vertaalt zich nooit naar de baan.' },
        { title: 'Slimmer, niet helemaal opnieuw', text: 'U wilt beter spelen zonder alles opnieuw op te bouwen.' },
      ],
    },
    finalCta: { eyebrow: 'Klaar om beter te spelen?', title: 'Neem contact op om een sessie te bespreken.', body: 'Vertel me waar uw spel nu staat en wat u wilt bereiken.', primaryCta: 'Neem contact op →', secondaryCta: 'Bekijk alle experiences' },
  },
  sv: {
    locale: 'sv',
    imageAlt: 'Andy Griffiths coachar golf pa Mallorca',
    hero: { breadcrumbHome: 'Hem', breadcrumbCurrent: 'On-Course Coaching', title: 'Battre golf. Utan att andra allt.', body: 'On-course coaching for besokande och bofasta golfare. Riktiga forhallanden, riktiga beslut och riktig forbattring, utan teknisk overload.' },
    range: {
      eyebrow: 'Varfor rangen inte racker',
      title: 'Det finns en anledning till att ditt rangspel inte syns pa banan.',
      paragraphs: ['Rangen ar platt, kontrollerad och utan verkliga konsekvenser. Pa banan syns vad som faktiskt hanger med.', 'On-course coaching placerar lektionen dar den hjalper: pa fairway, i ruffen, i vinden och nar score betyder nagot.'],
      quote: 'Forsta tee ar inte driving rangen.',
      quoteAttribution: 'Andy Griffiths, PGA Advanced Professional',
      questionnaireEyebrow: 'Fragestallningen',
      questionnaireParagraphs: ['Ett kort formulär formar dagen innan vi borjar.', 'Vid forsta tee vet jag redan vad jag letar efter.', 'Sessioner sker pa Son Gual, Alcanada eller en bana som passar dig.'],
      questionnaireCta: 'Diskutera en session →',
    },
    improvements: {
      eyebrow: 'Vad som verkligen blir battre',
      title: 'Det har forandras under en rond med mig.',
      sub: 'Och darfor sitter det kvar.',
      items: [
        { num: '01', title: 'Banhantering', text: 'De flesta slag tappas pa fel beslut snarare an pa fel swing.' },
        { num: '02', title: 'Slagval under press', text: 'Beslut under press blir synliga pa banan.' },
        { num: '03', title: 'Lasa greener och lutningar', text: 'Fart, lutning och grain andrar vad som fungerar.' },
        { num: '04', title: 'Spela i vind', text: 'Den verkliga vinden pa Mallorca krav er riktiga beslut.' },
        { num: '05', title: 'Mentalt spel och rutin', text: 'Det mentala visar sig pa riktigt nar konsekvenserna blir verkliga.' },
        { num: '06', title: 'Hitta de snabbaste vinsterna', text: 'En eller tva sma justeringar ger ofta mer an en total ombyggnad.' },
      ],
    },
    how: {
      eyebrow: 'Hur det fungerar',
      title: 'Tre steg. En session som forandrar hur du spelar.',
      body: 'Vi spelar tillsammans pa banan. Coachingen kommer i ratt ogonblick och feedbacken ar tydlig och anvandbar.',
      steps: [
        { num: '01', title: 'Fragestallningen', text: 'Fore sessionen fyller du i ett kort formular.' },
        { num: '02', title: 'Ronden', text: 'Ratt observation kommer precis nar den behovs.' },
        { num: '03', title: 'Genomgangen', text: 'Over lunch klargor vi vad som blev battre och vad du ska ta med dig.' },
      ],
    },
    who: {
      eyebrow: 'Vem det ar for',
      title: 'Om nagot av det har later bekant ar det for dig.',
      cards: [
        { title: 'Besokande golfare', text: 'Fokuserad forbattring under din tid pa on.' },
        { title: 'Bofasta golfare', text: 'Regelbundet arbete med en professionell som kan samma banor.' },
        { title: 'Gapet mellan range och bana', text: 'Ditt ovningsspel foljer aldrig med ut pa banan.' },
        { title: 'Smartare, inte total ombyggnad', text: 'Du vill spela battre utan att bygga om allt fran borjan.' },
      ],
    },
    finalCta: { eyebrow: 'Redo att spela battre?', title: 'Hor av dig for att diskutera en session.', body: 'Beratta var ditt spel star idag och vad du vill fa ut av det.', primaryCta: 'Kontakta mig →', secondaryCta: 'Se alla experiences' },
  },
  zh: {
    locale: 'zh',
    imageAlt: 'Andy Griffiths zai Mallorca jinxing gaoerfu zhidao',
    hero: { breadcrumbHome: 'Shouye', breadcrumbCurrent: 'Qiuchang zhidao', title: 'Da de geng hao. Bu yong gaibian yiqie.', body: 'Wei laifang he changzhu qiushou tigong qiuchang shizhan zhidao. Zhenshi tiaojian, zhenshi juece he zhenshi jinbu, meiyou jishu guozai.' },
    range: {
      eyebrow: 'Weishenme lianxi chang bu gou',
      title: 'Ni zai lianxi chang de biaoxian meiyou dai dao qiuchang shang, shi you yuanyin de.',
      paragraphs: ['Lianxi chang shi ping de, ke kong de, ye meiyou shenme houguo. Dao le di yi ge tee, zhenzheng de qingkuang cai kaishi.', 'Qiuchang zhidao ba xunlian fang zai zhenzheng you bangzhu de difang: fairway, rough, feng he zhenzheng you yiyi de chengji qingjing.'],
      quote: 'Di yi ge tee bu shi lianxi chang.',
      quoteAttribution: 'Andy Griffiths, PGA Advanced Professional',
      questionnaireEyebrow: 'Wenjuan',
      questionnaireParagraphs: ['Yi fen duan wenjuan hui zai kaishi qian bang wo huading zhongdian.', 'Dao di yi ge tee shi, wo yijing zhidao yao guancha shenme.', 'Session keyi zai Son Gual, Alcanada huo qita shihe ni de qiuchang jinxing.'],
      questionnaireCta: 'Taolun yi ci session →',
    },
    improvements: {
      eyebrow: 'Zhenzheng hui bianhao de dongxi',
      title: 'Zhe xie shi gen wo da yi lun hui gaibian de.',
      sub: 'Ye shi weishenme ta neng liu xia lai.',
      items: [
        { num: '01', title: 'Qiuchang guanli', text: 'Da duoshu diu fen lai zi cuowu juece er bu shi cuowu swing.' },
        { num: '02', title: 'Yali xia de xuanze', text: 'Zai yali xia de juece zhiyou zai qiuchang shang cai hui zhenzheng xianxing.' },
        { num: '03', title: 'Dudong greens he xiepo', text: 'Sudu, xiepo he grain dou hui gaibian youxiao de banfa.' },
        { num: '04', title: 'Zai feng zhong da qiu', text: 'Mallorca de zhenshi feng hui qiangpo ni zuochu zhenshi de xuanze.' },
        { num: '05', title: 'Xinli cengmian he routine', text: 'Dang houguo bian de zhenshi shi, xinli cengmian cai hui zhenzheng xianshi chulai.' },
        { num: '06', title: 'Zhaodao zui kuai de tisheng dian', text: 'Yi liang ge xiao de tupo dian tongchang bi quanmian chongjian lai de geng kuai, geng youxiao.' },
      ],
    },
    how: {
      eyebrow: 'Ruhe jinxing',
      title: 'San ge jieduan. Yi ci gaibian ni daqiu fangshi de session.',
      body: 'Women zai qiuchang shang yiqi daqiu. Zhidao zai zui dui de shike chuxian, fankui qingchu, zhijie he keyi liji shiyong.',
      steps: [
        { num: '01', title: 'Wenjuan', text: 'Session qian ni hui wancheng yi fen jiandan de biaodan.' },
        { num: '02', title: 'Zhe yi lun', text: 'Zai zui guanjian de shike gei chu zhengque de guancha.' },
        { num: '03', title: 'Zongjie', text: 'Wu fan shihou women huigu shenme bianhao le, ni yinggai daizou shenme.' },
      ],
    },
    who: {
      eyebrow: 'Shi he shei',
      title: 'Ruguo zheli de yixie qingkuang ting qilai hen shuxi, zhe hen keneng jiu shi gei ni de.',
      cards: [
        { title: 'Laifang qiushou', text: 'Zai daoshang de shijian nei huode you zhendui xing de jinbu.' },
        { title: 'Changzhu qiushou', text: 'Yu yi wei shuoxi tongyang qiuchang de professional zuo changqi gongzuo.' },
        { title: 'Lianxi chang dao qiuchang de chaju', text: 'Ni zai lianxi chang de biaoxian zongshi dai bu dao qiuchang shang.' },
        { title: 'Geng congming, bu shi quanmian chongjian', text: 'Ni xiang da de geng hao, dan bu xiang ba yiqie cong tou kaishi.' },
      ],
    },
    finalCta: { eyebrow: 'Zhunbei hao da de geng hao le ma?', title: 'Lianxi wo, yiqi taolun yi ci session.', body: 'Gaosu wo ni de qiujv xianzai zai nali, ni xiwang dedao shenme.', primaryCta: 'Lianxi wo →', secondaryCta: 'Chakan all experiences' },
  },
}

export function getCoachingContent(locale = 'en') {
  return COACHING_CONTENT[locale] || COACHING_CONTENT.en
}
