export const CONTACT_CONTENT = {
  en: {
    locale: 'en',
    hero: {
      eyebrow: 'Get in touch',
      title: "Tell me what you're looking for. I'll sort the rest.",
      intro:
        "There are no booking systems here. Tell me your dates, your handicap, and what you want from the day. I'll come back to you personally, usually within a few hours, always within 24.",
    },
    cards: {
      emailLabel: 'Email',
      whatsappLabel: 'WhatsApp',
      whatsappValue: 'Message on WhatsApp →',
      responseLabel: 'Response time',
      responseValue: 'Within 24 hours - usually sooner',
      basedLabel: 'Based in',
      basedValue: 'Mallorca, Spain',
    },
    success: {
      title: 'Enquiry received.',
      body:
        "I'll come back to you personally, usually within a few hours, always within 24. If you'd prefer to speak directly, WhatsApp is the fastest route.",
    },
    form: {
      eyebrow: 'Enquiry form',
      title: 'Start planning your day.',
      intro: 'The more detail you give me, the better I can match the day to you.',
      labels: {
        fname: 'First name',
        lname: 'Last name',
        email: 'Email address',
        dates: 'Preferred dates',
        handicap: 'Your handicap',
        groupsize: 'Group size',
        experience: 'Which experience interests you?',
        message: 'Anything else I should know',
      },
      placeholders: {
        fname: 'Andy',
        lname: 'Smith',
        email: 'andy@example.com',
        dates: 'e.g. 15-22 October 2026',
        handicap: "e.g. 14, or 'beginner'",
        message:
          "Goals for the day, courses you've heard of, mixed group, specific requests - anything helps me build the right day for you.",
      },
      groupsizeOptions: [
        { value: '', label: 'Select group size' },
        { value: '1 - solo', label: '1 - solo' },
        { value: '2 - pair', label: '2 - pair' },
        { value: '3-4 - small group', label: '3-4 - small group' },
        { value: '5+ - larger group / corporate', label: '5+ - larger group / corporate' },
      ],
      experiences: [
        ['mallorca-round', 'The Mallorca Round', '€350 + green fee'],
        ['signature-day', 'The Signature Day', 'From €450 + green fee'],
        ['full-experience', 'The Full Experience', 'On enquiry'],
        ['not-sure', 'Not sure yet - advise me', ''],
      ],
      submit: 'Send Enquiry →',
      note: 'I respond personally to every enquiry within 24 hours. Your details are used only to arrange your experience.',
    },
  },
  de: {
    locale: 'de',
    hero: {
      eyebrow: 'Kontakt',
      title: 'Sagen Sie mir, was Sie suchen. Ich kuemmere mich um den Rest.',
      intro:
        'Kein Buchungssystem. Sagen Sie mir Ihre Daten, Ihr Handicap und was Sie sich von dem Tag erhoffen. Ich melde mich persoenlich bei Ihnen, meist innerhalb weniger Stunden, spaetestens innerhalb von 24 Stunden.',
    },
    cards: {
      emailLabel: 'E-Mail',
      whatsappLabel: 'WhatsApp',
      whatsappValue: 'Per WhatsApp schreiben →',
      responseLabel: 'Antwortzeit',
      responseValue: 'Innerhalb von 24 Stunden - meist schneller',
      basedLabel: 'Standort',
      basedValue: 'Mallorca, Spanien',
    },
    success: {
      title: 'Anfrage erhalten.',
      body: 'Ich melde mich persoenlich innerhalb von 24 Stunden. Wenn es schneller gehen soll, ist WhatsApp der einfachste Weg.',
    },
    form: {
      eyebrow: 'Anfrageformular',
      title: 'Beginnen Sie mit der Planung Ihres Tages.',
      intro: 'Je mehr Details Sie mir geben, desto besser kann ich den Tag auf Sie abstimmen.',
      labels: {
        fname: 'Vorname',
        lname: 'Nachname',
        email: 'E-Mail-Adresse',
        dates: 'Bevorzugte Termine',
        handicap: 'Ihr Handicap',
        groupsize: 'Gruppengroesse',
        experience: 'Welche Erfahrung interessiert Sie?',
        message: 'Was sollte ich sonst noch wissen?',
      },
      placeholders: {
        fname: 'Max',
        lname: 'Mustermann',
        email: 'max@beispiel.de',
        dates: 'z. B. 15.-22. Oktober 2026',
        handicap: "z. B. 14 oder 'Anfaenger'",
        message: 'Ziele fuer den Tag, Wunschplaetze, gemischte Gruppe, besondere Wuensche - alles hilft mir, den richtigen Tag fuer Sie zu planen.',
      },
      groupsizeOptions: [
        { value: '', label: 'Gruppengroesse waehlen' },
        { value: '1 - solo', label: '1 - allein' },
        { value: '2 - pair', label: '2 - zu zweit' },
        { value: '3-4 - small group', label: '3-4 - kleine Gruppe' },
        { value: '5+ - larger group / corporate', label: '5+ - groessere Gruppe / Firma' },
      ],
      experiences: [
        ['mallorca-round', 'Die Mallorca-Runde', '€350 + Greenfee'],
        ['signature-day', 'Der Signature Day', 'Ab €450 + Greenfee'],
        ['full-experience', 'Das volle Erlebnis', 'Auf Anfrage'],
        ['not-sure', 'Noch unsicher - bitte beraten Sie mich', ''],
      ],
      submit: 'Anfrage senden →',
      note: 'Ich beantworte jede Anfrage persoenlich innerhalb von 24 Stunden. Ihre Angaben nutze ich nur, um Ihren Tag zu planen.',
    },
  },
  es: {
    locale: 'es',
    hero: {
      eyebrow: 'Ponerse en contacto',
      title: 'Digame lo que busca. Yo me encargo del resto.',
      intro:
        'Sin sistemas de reserva. Digame sus fechas, su handicap y lo que quiere del dia. Le respondere personalmente, normalmente en unas horas y siempre dentro de 24.',
    },
    cards: {
      emailLabel: 'Correo electronico',
      whatsappLabel: 'WhatsApp',
      whatsappValue: 'Escribir por WhatsApp →',
      responseLabel: 'Tiempo de respuesta',
      responseValue: 'En 24 horas - normalmente antes',
      basedLabel: 'Ubicacion',
      basedValue: 'Mallorca, Espana',
    },
    success: {
      title: 'Consulta recibida.',
      body: 'Le respondere personalmente dentro de 24 horas. Si quiere hablar directamente, WhatsApp es la via mas rapida.',
    },
    form: {
      eyebrow: 'Formulario de consulta',
      title: 'Empiece a planificar su dia.',
      intro: 'Cuantos mas detalles me de, mejor podre adaptar el dia a usted.',
      labels: {
        fname: 'Nombre',
        lname: 'Apellido',
        email: 'Correo electronico',
        dates: 'Fechas preferidas',
        handicap: 'Su handicap',
        groupsize: 'Tamano del grupo',
        experience: 'Que experiencia le interesa?',
        message: 'Cualquier otra cosa que deba saber',
      },
      placeholders: {
        fname: 'Juan',
        lname: 'Garcia',
        email: 'juan@ejemplo.com',
        dates: 'p. ej. 15-22 octubre 2026',
        handicap: "p. ej. 14 o 'principiante'",
        message: 'Objetivos para el dia, campos que ha visto, grupo mixto, peticiones especificas: cualquier detalle ayuda.',
      },
      groupsizeOptions: [
        { value: '', label: 'Seleccione el tamano del grupo' },
        { value: '1 - solo', label: '1 - solo/a' },
        { value: '2 - pair', label: '2 - pareja' },
        { value: '3-4 - small group', label: '3-4 - grupo pequeno' },
        { value: '5+ - larger group / corporate', label: '5+ - grupo grande / empresa' },
      ],
      experiences: [
        ['mallorca-round', 'La Vuelta de Mallorca', '€350 + green fee'],
        ['signature-day', 'El Dia Signature', 'Desde €450 + green fee'],
        ['full-experience', 'La Experiencia Completa', 'A consultar'],
        ['not-sure', 'Aun no lo se - aconsejeme', ''],
      ],
      submit: 'Enviar consulta →',
      note: 'Respondo personalmente a cada consulta en 24 horas. Sus datos se usan solo para organizar su experiencia.',
    },
  },
  fr: {
    locale: 'fr',
    hero: {
      eyebrow: 'Prendre contact',
      title: "Dites-moi ce que vous cherchez. Je m'occupe du reste.",
      intro:
        'Pas de systeme de reservation. Donnez-moi vos dates, votre handicap et ce que vous attendez de la journee. Je vous repondrai personnellement, souvent en quelques heures, toujours sous 24 heures.',
    },
    cards: {
      emailLabel: 'E-mail',
      whatsappLabel: 'WhatsApp',
      whatsappValue: 'Ecrire sur WhatsApp →',
      responseLabel: 'Temps de reponse',
      responseValue: 'Sous 24 heures - souvent plus vite',
      basedLabel: 'Base a',
      basedValue: 'Majorque, Espagne',
    },
    success: {
      title: 'Demande recue.',
      body: 'Je vous repondrai personnellement sous 24 heures. Si vous preferez parler directement, WhatsApp est le plus rapide.',
    },
    form: {
      eyebrow: 'Formulaire de contact',
      title: 'Commencez a planifier votre journee.',
      intro: 'Plus vous me donnez de details, mieux je pourrai adapter la journee a vous.',
      labels: {
        fname: 'Prenom',
        lname: 'Nom',
        email: 'Adresse e-mail',
        dates: 'Dates souhaitees',
        handicap: 'Votre handicap',
        groupsize: 'Taille du groupe',
        experience: 'Quelle experience vous interesse ?',
        message: 'Autre chose que je devrais savoir',
      },
      placeholders: {
        fname: 'Jean',
        lname: 'Dupont',
        email: 'jean@exemple.com',
        dates: 'ex. 15-22 octobre 2026',
        handicap: "ex. 14 ou 'debutant'",
        message: 'Vos objectifs, les parcours que vous regardez, un groupe mixte, des demandes specifiques : tout m aide a preparer la bonne journee.',
      },
      groupsizeOptions: [
        { value: '', label: 'Choisir la taille du groupe' },
        { value: '1 - solo', label: '1 - seul(e)' },
        { value: '2 - pair', label: '2 - duo' },
        { value: '3-4 - small group', label: '3-4 - petit groupe' },
        { value: '5+ - larger group / corporate', label: '5+ - grand groupe / entreprise' },
      ],
      experiences: [
        ['mallorca-round', 'Le Tour de Majorque', '€350 + green fee'],
        ['signature-day', 'La Journee Signature', 'A partir de €450 + green fee'],
        ['full-experience', "L'Experience Complete", 'Sur devis'],
        ['not-sure', 'Pas encore certain(e) - conseillez-moi', ''],
      ],
      submit: 'Envoyer la demande →',
      note: 'Je reponds personnellement a chaque demande sous 24 heures. Vos coordonnees servent uniquement a organiser votre experience.',
    },
  },
  nl: {
    locale: 'nl',
    hero: {
      eyebrow: 'Neem contact op',
      title: 'Vertel me wat u zoekt. Ik regel de rest.',
      intro:
        'Geen boekingssysteem. Vertel me uw data, uw handicap en wat u van de dag wilt. Ik reageer persoonlijk, meestal binnen een paar uur en altijd binnen 24 uur.',
    },
    cards: {
      emailLabel: 'E-mail',
      whatsappLabel: 'WhatsApp',
      whatsappValue: 'Stuur een WhatsApp-bericht →',
      responseLabel: 'Reactietijd',
      responseValue: 'Binnen 24 uur - meestal sneller',
      basedLabel: 'Gevestigd in',
      basedValue: 'Mallorca, Spanje',
    },
    success: {
      title: 'Aanvraag ontvangen.',
      body: 'Ik reageer persoonlijk binnen 24 uur. Als u liever direct spreekt, is WhatsApp de snelste route.',
    },
    form: {
      eyebrow: 'Aanvraagformulier',
      title: 'Begin met het plannen van uw dag.',
      intro: 'Hoe meer details u me geeft, hoe beter ik de dag op u kan afstemmen.',
      labels: {
        fname: 'Voornaam',
        lname: 'Achternaam',
        email: 'E-mailadres',
        dates: 'Gewenste data',
        handicap: 'Uw handicap',
        groupsize: 'Groepsgrootte',
        experience: 'Welke ervaring interesseert u?',
        message: 'Iets anders wat ik moet weten',
      },
      placeholders: {
        fname: 'Jan',
        lname: 'de Vries',
        email: 'jan@voorbeeld.com',
        dates: 'bijv. 15-22 oktober 2026',
        handicap: "bijv. 14 of 'beginner'",
        message: 'Doelen voor de dag, banen die u op het oog heeft, gemengde groep, speciale wensen - elk detail helpt.',
      },
      groupsizeOptions: [
        { value: '', label: 'Kies groepsgrootte' },
        { value: '1 - solo', label: '1 - solo' },
        { value: '2 - pair', label: '2 - tweetal' },
        { value: '3-4 - small group', label: '3-4 - kleine groep' },
        { value: '5+ - larger group / corporate', label: '5+ - grotere groep / bedrijf' },
      ],
      experiences: [
        ['mallorca-round', 'De Mallorca-ronde', '€350 + green fee'],
        ['signature-day', 'De Signature Dag', 'Vanaf €450 + green fee'],
        ['full-experience', 'De volledige ervaring', 'Op aanvraag'],
        ['not-sure', 'Nog niet zeker - adviseer me', ''],
      ],
      submit: 'Aanvraag versturen →',
      note: 'Ik reageer persoonlijk op elke aanvraag binnen 24 uur. Uw gegevens worden alleen gebruikt om uw ervaring te organiseren.',
    },
  },
  sv: {
    locale: 'sv',
    hero: {
      eyebrow: 'Hor av dig',
      title: 'Beratta vad du soker. Jag ordnar resten.',
      intro:
        'Inga bokningssystem. Beratta om dina datum, ditt handicap och vad du vill fa ut av dagen. Jag svarar personligen, oftast inom nagra timmar och alltid inom 24 timmar.',
    },
    cards: {
      emailLabel: 'E-post',
      whatsappLabel: 'WhatsApp',
      whatsappValue: 'Skicka ett WhatsApp-meddelande →',
      responseLabel: 'Svarstid',
      responseValue: 'Inom 24 timmar - oftast snabbare',
      basedLabel: 'Bas i',
      basedValue: 'Mallorca, Spanien',
    },
    success: {
      title: 'Forfragan mottagen.',
      body: 'Jag aterkommer personligen inom 24 timmar. Om du vill prata direkt ar WhatsApp den snabbaste vagen.',
    },
    form: {
      eyebrow: 'Forfragan',
      title: 'Borja planera din dag.',
      intro: 'Ju mer detaljer du ger mig, desto battre kan jag anpassa dagen efter dig.',
      labels: {
        fname: 'Fornamn',
        lname: 'Efternamn',
        email: 'E-postadress',
        dates: 'Onskade datum',
        handicap: 'Ditt handicap',
        groupsize: 'Gruppstorlek',
        experience: 'Vilken upplevelse ar du intresserad av?',
        message: 'Nagot annat jag bor veta',
      },
      placeholders: {
        fname: 'Erik',
        lname: 'Svensson',
        email: 'erik@exempel.se',
        dates: 't.ex. 15-22 oktober 2026',
        handicap: "t.ex. 14 eller 'nyborjare'",
        message: 'Mal for dagen, banor du tittar pa, blandad grupp, sarskilda onskemal - allt hjalper mig att skapa ratt dag.',
      },
      groupsizeOptions: [
        { value: '', label: 'Valj gruppstorlek' },
        { value: '1 - solo', label: '1 - solo' },
        { value: '2 - pair', label: '2 - par' },
        { value: '3-4 - small group', label: '3-4 - liten grupp' },
        { value: '5+ - larger group / corporate', label: '5+ - storre grupp / foretag' },
      ],
      experiences: [
        ['mallorca-round', 'Mallorca-rundan', '€350 + green fee'],
        ['signature-day', 'Signature-dagen', 'Fran €450 + green fee'],
        ['full-experience', 'Den kompletta upplevelsen', 'Pa forfragan'],
        ['not-sure', 'Inte saker annu - ge mig rad', ''],
      ],
      submit: 'Skicka forfragan →',
      note: 'Jag svarar personligen pa varje forfragan inom 24 timmar. Dina uppgifter anvands bara for att planera din upplevelse.',
    },
  },
  zh: {
    locale: 'zh',
    hero: {
      eyebrow: 'Lianxi wo',
      title: 'Gaosu wo nin de xuqiu, qita jiao gei wo.',
      intro:
        'Zheli meiyou yuding xitong. Gaosu wo nin de riqi, chadian he nin xiangyao de tiyan. Wo hui qinzi huifu, tongchang zai jige xiaoshi nei, zuiwan 24 xiaoshi nei.',
    },
    cards: {
      emailLabel: 'Email',
      whatsappLabel: 'WhatsApp',
      whatsappValue: 'Tongguo WhatsApp lianxi →',
      responseLabel: 'Huifu shijian',
      responseValue: '24 xiaoshi nei - tongchang geng kuai',
      basedLabel: 'Suozai di',
      basedValue: 'Mallorca, Xibanya',
      wechatLabel: 'WeChat',
      wechatValue: 'andygriffiths1',
    },
    success: {
      title: 'Xunpan yi shoudao.',
      body: 'Wo hui zai 24 xiaoshi nei qinzi huifu nin. Ruguo nin xiang geng kuai goutong, WhatsApp shi zuikuai de fangshi.',
    },
    form: {
      eyebrow: 'Xunpan biaodan',
      title: 'Kaishi guihua nin de yi tian.',
      intro: 'Nin tigong de xinxi yue duo, wo jiu neng yue hao de wei nin dingzhi zhe yi tian.',
      labels: {
        fname: 'Ming',
        lname: 'Xing',
        email: 'Email dizhi',
        dates: 'Xiwang de riqi',
        handicap: 'Nin de chadian',
        groupsize: 'Renshu',
        experience: 'Nin dui na zhong tiyan gan xingqu?',
        message: 'Hai you shenme xuyao wo zhidao',
      },
      placeholders: {
        fname: 'Wei',
        lname: 'Zhang',
        email: 'zhang@example.com',
        dates: 'li ru 2026 nian 10 yue 15-22 ri',
        handicap: "li ru 14 huo 'chuxuezhe'",
        message: 'Dangtian mubiao, xiang qu de qiuchang, hunhe tuandui huo teshu xuqiu - renhe xijie dou hui you bangzhu.',
      },
      groupsizeOptions: [
        { value: '', label: 'Xuanze renshu' },
        { value: '1 - solo', label: '1 ren - dandu' },
        { value: '2 - pair', label: '2 ren - shuangren' },
        { value: '3-4 - small group', label: '3-4 ren - xiaozu' },
        { value: '5+ - larger group / corporate', label: '5 ren yishang - da tuandui / gongsi' },
      ],
      experiences: [
        ['mallorca-round', 'Mallorca jingdian yi ri', '€350 + green fee'],
        ['signature-day', 'Signature yi ri tiyan', '€450 qi + green fee'],
        ['full-experience', 'Quanmian dingzhi tiyan', 'Juti mianyi'],
        ['not-sure', 'Hai bu queding - qing gei wo jianyi', ''],
      ],
      submit: 'Tijiao xunpan →',
      note: 'Wo hui zai 24 xiaoshi nei qinzi huifu mei yi feng xunpan. Nin de xinxi zhi yong yu anpai nin de tiyan.',
    },
  },
}

export function getContactContent(locale = 'en') {
  return CONTACT_CONTENT[locale] || CONTACT_CONTENT.en
}
