import { getContactExperienceOptions } from './offers-content.js'

export const CONTACT_CONTENT = {
  en: {
    locale: 'en',
    hero: {
      eyebrow: 'Get in touch',
      title: "Tell me what you're looking for. I'll sort the rest.",
      intro:
        "There are no booking systems here. Tell me your dates, your handicap, and what you want from the day. I'll come back to you personally, usually within a few hours and always within 24.",
    },
    cards: {
      emailLabel: 'Email',
      whatsappLabel: 'WhatsApp',
      whatsappValue: 'Message on WhatsApp →',
      responseLabel: 'Response time',
      responseValue: 'Within 24 hours - usually sooner',
      basedLabel: 'Based in',
      basedValue: 'Mallorca, Spain',
    },
    success: {
      title: 'Enquiry received.',
      body:
        "I'll come back to you personally, usually within a few hours, always within 24. If you'd prefer to speak directly, WhatsApp is the fastest route.",
    },
    form: {
      eyebrow: 'Enquiry form',
      title: 'Start planning your day.',
      intro: 'The more detail you give me, the better I can match the day to you and your golf.',
      labels: {
        fname: 'First name',
        lname: 'Last name',
        email: 'Email address',
        dates: 'Preferred dates',
        handicap: 'Your handicap',
        groupsize: 'Group size',
        experience: 'Which experience interests you?',
        message: 'Anything else I should know',
      },
      placeholders: {
        fname: 'Andy',
        lname: 'Smith',
        email: 'andy@example.com',
        dates: 'e.g. 15-22 October 2026',
        handicap: "e.g. 14, or 'beginner'",
        message:
          "Goals for the day, courses you've heard of, mixed group, specific requests - anything helps me build the right day for you.",
      },
      groupsizeOptions: [
        { value: '', label: 'Select group size' },
        { value: '1 - solo', label: '1 - solo' },
        { value: '2 - pair', label: '2 - pair' },
        { value: '3-4 - small group', label: '3-4 - small group' },
        { value: '5+ - larger group / corporate', label: '5+ - larger group / corporate' },
      ],
      experiences: [
        ['mallorca-round', 'A Day With Andy - Solo', '€495'],
        ['signature-day', 'A Day With Andy - Group', '€950'],
        ['full-andy-day', 'A Day With Andy - Signature Experience', 'From €3,000'],
        ['not-sure', 'Not sure yet - advise me', ''],
      ],
      submit: 'Send Enquiry →',
      note: 'I respond personally to every enquiry within 24 hours. Your details are used only to arrange your day.',
    },
    gift: {
      heading: 'Buying this as a gift?',
      body: "Let me know in the message above and I'll prepare a certificate and keep the day details private until you're ready to share them.",
    },
    whatNext: {
      heading: 'What happens next',
      body: 'I read every enquiry personally. You\'ll hear from me within 24 hours with a course recommendation and next steps — usually sooner. If you prefer to talk directly, WhatsApp is the fastest route.',
    },
    stayInTouch: {
      heading: 'Stay in touch',
      body: 'Course notes and Mallorca golf insights every two weeks — straight to your inbox.',
    },
    dateCta: 'Tell Me Your Dates',
  },
  de: {
    locale: 'de',
    hero: {
      eyebrow: 'Kontakt',
      title: 'Sagen Sie mir, was Sie suchen. Ich kümmere mich um den Rest.',
      intro:
        'Kein Buchungssystem. Sagen Sie mir Ihre Daten, Ihr Handicap und was Sie sich von dem Tag erhoffen. Ich melde mich persönlich bei Ihnen, meist innerhalb weniger Stunden und immer innerhalb von 24 Stunden.',
    },
    cards: {
      emailLabel: 'E-Mail',
      whatsappLabel: 'WhatsApp',
      whatsappValue: 'Per WhatsApp schreiben →',
      responseLabel: 'Antwortzeit',
      responseValue: 'Innerhalb von 24 Stunden - meist schneller',
      basedLabel: 'Standort',
      basedValue: 'Mallorca, Spanien',
    },
    success: {
      title: 'Anfrage erhalten.',
      body: 'Ich melde mich persönlich innerhalb von 24 Stunden. Wenn es schneller gehen soll, ist WhatsApp der einfachste Weg.',
    },
    form: {
      eyebrow: 'Anfrageformular',
      title: 'Beginnen Sie mit der Planung Ihres Tages.',
      intro: 'Je mehr Details Sie mir geben, desto besser kann ich den Tag auf Sie abstimmen.',
      labels: {
        fname: 'Vorname',
        lname: 'Nachname',
        email: 'E-Mail-Adresse',
        dates: 'Bevorzugte Termine',
        handicap: 'Ihr Handicap',
        groupsize: 'Gruppengröße',
        experience: 'Welche Option passt am besten?',
        message: 'Was sollte ich sonst noch wissen?',
      },
      placeholders: {
        fname: 'Max',
        lname: 'Mustermann',
        email: 'max@beispiel.de',
        dates: 'z. B. 15.-22. Oktober 2026',
        handicap: "z. B. 14 oder 'Anfänger'",
        message: 'Ziele für den Tag, Wunschplätze, gemischte Gruppe, besondere Wünsche - alles hilft mir, den richtigen Tag für Sie zu planen.',
      },
      groupsizeOptions: [
        { value: '', label: 'Gruppengröße wählen' },
        { value: '1 - solo', label: '1 - allein' },
        { value: '2 - pair', label: '2 - zu zweit' },
        { value: '3-4 - small group', label: '3-4 - kleine Gruppe' },
        { value: '5+ - larger group / corporate', label: '5+ - größere Gruppe / Firma' },
      ],
      experiences: [
        ['mallorca-round', 'Ein Tag mit Andy - Solo', '€495'],
        ['signature-day', 'Ein Tag mit Andy - Gruppe', '€950 + Greenfees'],
        ['full-experience', 'Mehrtägige Reise', 'Auf Anfrage'],
        ['not-sure', 'Noch unsicher - beraten Sie mich', ''],
      ],
      submit: 'Anfrage senden →',
      note: 'Ich beantworte jede Anfrage persönlich innerhalb von 24 Stunden. Ihre Angaben nutze ich nur, um Ihren Tag zu planen.',
    },
    gift: {
      heading: 'Schenken Sie diesen Tag?',
      body: 'Teilen Sie mir das bitte in der Nachricht oben mit. Ich bereite dann ein Zertifikat vor und halte die Details zur Erfahrung zurück, bis Sie bereit sind, sie zu teilen.',
    },
    whatNext: {
      heading: 'Was passiert als Nächstes?',
      body: 'Ich lese jede Anfrage persönlich. Sie hören von mir innerhalb von 24 Stunden mit einer Kursempfehlung und den nächsten Schritten — normalerweise früher. Wenn Sie lieber direkt sprechen möchten, ist WhatsApp am schnellsten.',
    },
    stayInTouch: {
      heading: 'In Kontakt bleiben',
      body: 'Platz-Updates und Mallorca-Golf-Einblicke alle zwei Wochen — direkt in Ihr Postfach.',
    },
    dateCta: 'Meine Daten mitteilen',
  },
  es: {
    locale: 'es',
    hero: {
      eyebrow: 'Ponerse en contacto',
      title: 'Dígame qué busca. Yo me encargo del resto.',
      intro:
        'Sin sistemas de reserva. Dígame sus fechas, su hándicap y lo que quiere del día. Le responderé personalmente, normalmente en unas horas y siempre dentro de 24.',
    },
    cards: {
      emailLabel: 'Correo electrónico',
      whatsappLabel: 'WhatsApp',
      whatsappValue: 'Escribir por WhatsApp →',
      responseLabel: 'Tiempo de respuesta',
      responseValue: 'En 24 horas - normalmente antes',
      basedLabel: 'Ubicación',
      basedValue: 'Mallorca, España',
    },
    success: {
      title: 'Consulta recibida.',
      body: 'Le responderé personalmente dentro de 24 horas. Si quiere hablar directamente, WhatsApp es la vía más rápida.',
    },
    form: {
      eyebrow: 'Formulario de consulta',
      title: 'Empiece a planificar su día.',
      intro: 'Cuantos más detalles me dé, mejor podré adaptar el día a usted.',
      labels: {
        fname: 'Nombre',
        lname: 'Apellido',
        email: 'Correo electrónico',
        dates: 'Fechas preferidas',
        handicap: 'Su hándicap',
        groupsize: 'Tamaño del grupo',
        experience: '¿Qué opción le encaja mejor?',
        message: 'Cualquier otra cosa que deba saber',
      },
      placeholders: {
        fname: 'Juan',
        lname: 'García',
        email: 'juan@ejemplo.com',
        dates: 'p. ej. 15-22 octubre 2026',
        handicap: 'p. ej. 14 o "principiante"',
        message: 'Objetivos para el día, campos que ha visto, grupo mixto, peticiones específicas: cualquier detalle ayuda.',
      },
      groupsizeOptions: [
        { value: '', label: 'Seleccione el tamaño del grupo' },
        { value: '1 - solo', label: '1 - solo/a' },
        { value: '2 - pair', label: '2 - pareja' },
        { value: '3-4 - small group', label: '3-4 - grupo pequeño' },
        { value: '5+ - larger group / corporate', label: '5+ - grupo grande / empresa' },
      ],
      experiences: [
        ['mallorca-round', 'Un día con Andy - Solo', '€495'],
        ['signature-day', 'Un día con Andy - Grupo', '€950 + green fees'],
        ['full-experience', 'Viaje de varios días', 'A consultar'],
        ['not-sure', 'Aún no lo sé - aconséjeme', ''],
      ],
      submit: 'Enviar consulta →',
      note: 'Respondo personalmente a cada consulta en 24 horas. Sus datos se usan solo para organizar su jornada.',
    },
    gift: {
      heading: '¿Es un regalo?',
      body: 'Indíquemelo en el mensaje de arriba y prepararé un certificado, manteniendo los detalles del día en privado hasta que esté listo para compartirlos.',
    },
    whatNext: {
      heading: 'Qué ocurre a continuación',
      body: 'Leo cada consulta personalmente. Le responderé en 24 horas con una recomendación de campo y los próximos pasos — normalmente antes. Si prefiere hablar directamente, WhatsApp es la vía más rápida.',
    },
    stayInTouch: {
      heading: 'Mantenerse en contacto',
      body: 'Notas sobre campos y consejos de golf en Mallorca cada dos semanas — directamente en su bandeja de entrada.',
    },
    dateCta: 'Dígame sus fechas',
  },
  fr: {
    locale: 'fr',
    hero: {
      eyebrow: 'Prendre contact',
      title: "Dites-moi ce que vous cherchez. Je m'occupe du reste.",
      intro:
        'Pas de système de réservation. Donnez-moi vos dates, votre handicap et ce que vous attendez de la journée. Je vous répondrai personnellement, souvent en quelques heures et toujours sous 24 heures.',
    },
    cards: {
      emailLabel: 'E-mail',
      whatsappLabel: 'WhatsApp',
      whatsappValue: 'Écrire sur WhatsApp →',
      responseLabel: 'Délai de réponse',
      responseValue: 'Sous 24 heures - souvent plus vite',
      basedLabel: 'Basé à',
      basedValue: 'Majorque, Espagne',
    },
    success: {
      title: 'Demande reçue.',
      body: 'Je vous répondrai personnellement sous 24 heures. Si vous préférez parler directement, WhatsApp est le plus rapide.',
    },
    form: {
      eyebrow: 'Formulaire de contact',
      title: 'Commencez à planifier votre journée.',
      intro: 'Plus vous me donnez de détails, mieux je pourrai adapter la journée à vous.',
      labels: {
        fname: 'Prénom',
        lname: 'Nom',
        email: 'Adresse e-mail',
        dates: 'Dates souhaitées',
        handicap: 'Votre handicap',
        groupsize: 'Taille du groupe',
        experience: 'Quelle formule vous convient le mieux ?',
        message: 'Autre chose que je devrais savoir',
      },
      placeholders: {
        fname: 'Jean',
        lname: 'Dupont',
        email: 'jean@exemple.com',
        dates: 'ex. 15-22 octobre 2026',
        handicap: "ex. 14 ou 'débutant'",
        message: 'Vos objectifs, les parcours que vous regardez, un groupe mixte, des demandes spécifiques : tout m’aide à préparer la bonne journée.',
      },
      groupsizeOptions: [
        { value: '', label: 'Choisir la taille du groupe' },
        { value: '1 - solo', label: '1 - seul(e)' },
        { value: '2 - pair', label: '2 - duo' },
        { value: '3-4 - small group', label: '3-4 - petit groupe' },
        { value: '5+ - larger group / corporate', label: '5+ - grand groupe / entreprise' },
      ],
      experiences: [
        ['mallorca-round', 'Une journée avec Andy - Solo', '€495'],
        ['signature-day', 'Une journée avec Andy - Groupe', '€950'],
        ['full-experience', 'Séjour sur plusieurs jours', 'Sur demande'],
        ['not-sure', 'Je ne suis pas encore certain(e) - conseillez-moi', ''],
      ],
      submit: 'Envoyer la demande →',
      note: 'Je réponds personnellement à chaque demande sous 24 heures. Vos coordonnées servent uniquement à organiser votre journée.',
    },
    gift: {
      heading: 'Vous offrez cette journée ?',
      body: "Mentionnez-le dans le message ci-dessus et je préparerai un certificat, en gardant les détails confidentiels jusqu'à ce que vous soyez prêt à les partager.",
    },
    whatNext: {
      heading: 'Que se passe-t-il ensuite ?',
      body: 'Je lis chaque demande personnellement. Vous aurez de mes nouvelles sous 24 heures avec une recommandation de parcours et les prochaines étapes — souvent plus tôt. Si vous préférez parler directement, WhatsApp est le plus rapide.',
    },
    stayInTouch: {
      heading: 'Rester en contact',
      body: 'Notes de parcours et conseils golf à Majorque toutes les deux semaines — directement dans votre boîte mail.',
    },
    dateCta: 'Dites-moi vos dates',
  },
  nl: {
    locale: 'nl',
    hero: {
      eyebrow: 'Neem contact op',
      title: 'Vertel me wat u zoekt. Ik regel de rest.',
      intro:
        'Geen boekingssysteem. Vertel me uw data, uw handicap en wat u van de dag wilt. Ik reageer persoonlijk, meestal binnen een paar uur en altijd binnen 24 uur.',
    },
    cards: {
      emailLabel: 'E-mail',
      whatsappLabel: 'WhatsApp',
      whatsappValue: 'Stuur een WhatsApp-bericht →',
      responseLabel: 'Reactietijd',
      responseValue: 'Binnen 24 uur - meestal sneller',
      basedLabel: 'Gevestigd in',
      basedValue: 'Mallorca, Spanje',
    },
    success: {
      title: 'Aanvraag ontvangen.',
      body: 'Ik reageer persoonlijk binnen 24 uur. Als u liever direct spreekt, is WhatsApp de snelste route.',
    },
    form: {
      eyebrow: 'Aanvraagformulier',
      title: 'Begin met het plannen van uw dag.',
      intro: 'Hoe meer details u me geeft, hoe beter ik de dag op u kan afstemmen.',
      labels: {
        fname: 'Voornaam',
        lname: 'Achternaam',
        email: 'E-mailadres',
        dates: 'Gewenste data',
        handicap: 'Uw handicap',
        groupsize: 'Groepsgrootte',
        experience: 'Welke optie past het best?',
        message: 'Is er verder nog iets dat ik moet weten?',
      },
      placeholders: {
        fname: 'Jan',
        lname: 'de Vries',
        email: 'jan@voorbeeld.com',
        dates: 'bijv. 15-22 oktober 2026',
        handicap: "bijv. 14 of 'beginner'",
        message: 'Doelen voor de dag, banen die u op het oog heeft, gemengde groep, speciale wensen - elk detail helpt.',
      },
      groupsizeOptions: [
        { value: '', label: 'Kies groepsgrootte' },
        { value: '1 - solo', label: '1 - solo' },
        { value: '2 - pair', label: '2 - tweetal' },
        { value: '3-4 - small group', label: '3-4 - kleine groep' },
        { value: '5+ - larger group / corporate', label: '5+ - grotere groep / bedrijf' },
      ],
      experiences: [
        ['mallorca-round', 'Een dag met Andy - Solo', '€495'],
        ['signature-day', 'Een dag met Andy - Groep', '€950'],
        ['full-experience', 'Meerdaagse reis', 'Op aanvraag'],
        ['not-sure', 'Nog niet zeker - adviseer me', ''],
      ],
      submit: 'Aanvraag versturen →',
      note: 'Ik reageer persoonlijk op elke aanvraag binnen 24 uur. Uw gegevens worden alleen gebruikt om uw dag te organiseren.',
    },
    gift: {
      heading: 'Is dit een cadeau?',
      body: 'Vermeld het in het bericht hierboven en ik maak een certificaat klaar, waarbij ik de details van de dag privé houd totdat u klaar bent om ze te delen.',
    },
    whatNext: {
      heading: 'Wat gebeurt er daarna?',
      body: 'Ik lees elke aanvraag persoonlijk. U hoort binnen 24 uur van mij met een baanaanbeveling en de volgende stappen — meestal eerder. Als u liever direct spreekt, is WhatsApp de snelste route.',
    },
    stayInTouch: {
      heading: 'Blijf op de hoogte',
      body: 'Baannotities en Mallorca golf-inzichten elke twee weken — rechtstreeks in uw inbox.',
    },
    dateCta: 'Vertel me uw data',
  },
  sv: {
    locale: 'sv',
    hero: {
      eyebrow: 'Hör av dig',
      title: 'Berätta vad du söker. Jag ordnar resten.',
      intro:
        'Inga bokningssystem. Berätta om dina datum, ditt handicap och vad du vill få ut av dagen. Jag svarar personligen, oftast inom några timmar och alltid inom 24 timmar.',
    },
    cards: {
      emailLabel: 'E-post',
      whatsappLabel: 'WhatsApp',
      whatsappValue: 'Skicka ett WhatsApp-meddelande →',
      responseLabel: 'Svarstid',
      responseValue: 'Inom 24 timmar - oftast snabbare',
      basedLabel: 'Bas i',
      basedValue: 'Mallorca, Spanien',
    },
    success: {
      title: 'Förfrågan mottagen.',
      body: 'Jag återkommer personligen inom 24 timmar. Om du vill prata direkt är WhatsApp den snabbaste vägen.',
    },
    form: {
      eyebrow: 'Förfrågan',
      title: 'Börja planera din dag.',
      intro: 'Ju mer detaljer du ger mig, desto bättre kan jag anpassa dagen efter dig.',
      labels: {
        fname: 'Förnamn',
        lname: 'Efternamn',
        email: 'E-postadress',
        dates: 'Önskade datum',
        handicap: 'Ditt handicap',
        groupsize: 'Gruppstorlek',
        experience: 'Vilket upplägg passar dig bäst?',
        message: 'Något annat jag bör veta',
      },
      placeholders: {
        fname: 'Erik',
        lname: 'Svensson',
        email: 'erik@exempel.se',
        dates: 't.ex. 15-22 oktober 2026',
        handicap: "t.ex. 14 eller 'nybörjare'",
        message: 'Mål för dagen, banor du tittar på, blandad grupp, särskilda önskemål - allt hjälper mig att skapa rätt dag.',
      },
      groupsizeOptions: [
        { value: '', label: 'Välj gruppstorlek' },
        { value: '1 - solo', label: '1 - solo' },
        { value: '2 - pair', label: '2 - par' },
        { value: '3-4 - small group', label: '3-4 - liten grupp' },
        { value: '5+ - larger group / corporate', label: '5+ - större grupp / företag' },
      ],
      experiences: [
        ['mallorca-round', 'En dag med Andy - Solo', '€495'],
        ['signature-day', 'En dag med Andy - Grupp', '€950'],
        ['full-experience', 'Flerdagarsresa', 'På förfrågan'],
        ['not-sure', 'Inte säker ännu - ge mig råd', ''],
      ],
      submit: 'Skicka förfrågan →',
      note: 'Jag svarar personligen på varje förfrågan inom 24 timmar. Dina uppgifter används bara för att planera din dag.',
    },
    gift: {
      heading: 'Köper du detta som en present?',
      body: 'Berätta det i meddelandet ovan så förbereder jag ett presentkort och håller dagsinformationen privat tills du är redo att dela den.',
    },
    whatNext: {
      heading: 'Vad händer härnäst?',
      body: 'Jag läser varje förfrågan personligen. Du hör av mig inom 24 timmar med en banrekommendation och nästa steg — oftast snabbare. Om du föredrar att prata direkt är WhatsApp snabbast.',
    },
    stayInTouch: {
      heading: 'Håll kontakten',
      body: 'Bannoteringar och golfinblickar från Mallorca varannan vecka — direkt till din inkorg.',
    },
    dateCta: 'Berätta dina datum',
  },
  zh: {
    locale: 'zh',
    hero: {
      eyebrow: '联系我',
      title: '告诉我您想要怎样的一天。其余的我来安排。',
      intro:
        '这里没有自动预订系统。告诉我您的日期、差点以及您希望这一天达到什么效果。我会亲自回复您，通常几小时内，最晚不超过 24 小时。',
    },
    cards: {
      emailLabel: '电子邮箱',
      whatsappLabel: 'WhatsApp',
      whatsappValue: '通过 WhatsApp 联系 →',
      responseLabel: '回复时间',
      responseValue: '24 小时内 - 通常更快',
      basedLabel: '所在地',
      basedValue: '马略卡，西班牙',
      wechatLabel: '微信',
      wechatValue: 'andygriffiths1',
    },
    success: {
      title: '已收到您的咨询。',
      body: '我会在 24 小时内亲自回复您。如果您希望更快沟通，WhatsApp 是最直接的方式。',
    },
    form: {
      eyebrow: '咨询表单',
      title: '开始安排您的这一天。',
      intro: '您提供的信息越详细，我就越能把这一天安排得更贴合您的球和您的需求。',
      labels: {
        fname: '名字',
        lname: '姓氏',
        email: '电子邮箱',
        dates: '希望的日期',
        handicap: '您的差点',
        groupsize: '人数',
        experience: '您更想了解哪种安排？',
        message: '还有什么我应该知道的？',
      },
      placeholders: {
        fname: '张',
        lname: '先生',
        email: 'zhang@example.com',
        dates: '例如 2026 年 10 月 15-22 日',
        handicap: "例如 14 或 '初学者'",
        message: '这一天的目标、您在考虑的球场、是否为混合水平小组、特别要求等，任何信息都能帮助我安排得更准确。',
      },
      groupsizeOptions: [
        { value: '', label: '选择人数' },
        { value: '1 - solo', label: '1 人 - 单人' },
        { value: '2 - pair', label: '2 人 - 双人' },
        { value: '3-4 - small group', label: '3-4 人 - 小组' },
        { value: '5+ - larger group / corporate', label: '5 人以上 - 团队 / 公司' },
      ],
      experiences: [
        ['mallorca-round', '与 Andy 共度一天 - 单人', '€495'],
        ['signature-day', '与 Andy 共度一天 - 小组', '€950'],
        ['full-experience', '多日行程', '按需报价'],
        ['not-sure', '暂时不确定 - 请给我建议', ''],
      ],
      submit: '发送咨询 →',
      note: '我会在 24 小时内亲自回复每一条咨询。您的信息只会用于安排您的这一天。',
    },
    gift: {
      heading: '这是一份礼物？',
      body: '请在上方留言告知我，我会准备一张礼品证书，并在您准备好分享之前保密行程细节。',
    },
    whatNext: {
      heading: '接下来会发生什么',
      body: '我会亲自阅读每一条咨询。24 小时内您将收到我的回复，包括球场推荐和后续步骤——通常更快。如果您希望直接沟通，WhatsApp 是最快的方式。',
    },
    stayInTouch: {
      heading: '保持联系',
      body: '每两周发送一次马略卡球场动态和高尔夫资讯——直接发送到您的收件箱。',
    },
    dateCta: '告诉我您的日期',
  },
}

export function getContactContent(locale = 'en') {
  const content = CONTACT_CONTENT[locale] || CONTACT_CONTENT.en

  return {
    ...content,
    form: {
      ...content.form,
      experiences: getContactExperienceOptions(locale),
    },
  }
}
