export const HOME_CONTENT = {
  en: {
    locale: 'en',
    hero: {
      eyebrow: 'UK PGA Advanced Professional · Mallorca',
      titleLines: ["Play Mallorca's", 'Best Courses.'],
      emphasis: 'With a Pro by Your Side.',
      primaryCta: 'Book Your Day',
      secondaryCta: 'Explore Courses',
      trust: [
        'PGA Advanced Professional',
        'Trackman Master Certified',
        '18 Years Coaching Golf',
        'Pebble Beach · Evian · The Open',
      ],
    },
    intro: {
      eyebrow: 'What sets this apart',
      title: 'Most golf days in Mallorca start with a booking platform and end with a bill. This is more personal.',
      body: 'I host private golf days on the island\'s best courses, with the coaching given during the round rather than as an add-on afterwards. The golf is better, the decisions are clearer, and the whole day feels properly looked after.',
      stats: [
        { value: '18', label: 'Years coaching golf' },
        { value: '15,000+', label: 'Lessons delivered' },
        { value: '300+', label: 'Competition winners coached' },
      ],
    },
    socialProof: 'Andy 教练 · 300 million+ golf coaching video views on TikTok · Coaching content trusted worldwide',
    how: {
      eyebrow: 'How it works',
      title: 'Three simple steps.',
      steps: [
        {
          number: '01',
          title: 'Get in touch',
          text: "Tell me your dates, your handicap, and what you're looking for. I reply personally within 24 hours.",
        },
        {
          number: '02',
          title: 'I build your day',
          text: 'Course recommendation, tee time, lunch, and transport are all arranged before you arrive.',
        },
        {
          number: '03',
          title: 'Show up and play',
          text: "Your job is to enjoy the round. Most people play better than they expected to.",
        },
      ],
    },
    whyMallorca: {
      eyebrow: 'Why Mallorca',
      title: 'Mallorca has European Tour-standard courses. Many visitors play a few and never discover the rest.',
      paragraphs: [
        "Most of Europe's best golf courses close in winter. Mallorca does not. October through April is the sweet spot: lower green fees, quieter courses, and conditions that would shame a summer round elsewhere.",
        'Twenty-two courses sit within easy reach, several with DP World Tour pedigree and serious design history. Mallorca is a proper golf destination, and most visitors only scratch the surface.',
      ],
      stats: [
        { value: '22', label: 'courses on the island' },
        { value: '300+', label: 'days of sunshine per year' },
        { value: 'Jan-Dec', label: 'year-round season' },
        { value: '€80-220', label: 'green fee range' },
      ],
    },
    courses: {
      eyebrow: 'Featured Courses',
      title: "Mallorca's finest, played and reviewed.",
      viewAll: 'View all 22 courses →',
      items: [
        {
          cls: 'course-card--1',
          badge: 'Expert Pick',
          region: 'Palma · 11 km from city',
          name: 'Son Gual',
          meta: ['Championship', 'Par 72', '€80-165'],
          stars: '★★★★★',
          difficulty: '9/10 Difficulty',
          excerpt: "Thomas Himmel's 2007 design lives in its own wind ecosystem. The closing stretch from 15 through 18 is among the finest in European golf.",
          img: '/images/son-gual.jpg',
          href: '/guides/son-gual-review',
        },
        {
          cls: 'course-card--2',
          badge: 'Expert Pick',
          region: 'Alcudia · North Mallorca',
          name: 'Alcanada',
          meta: ['Coastal', 'Par 72', '€115-220'],
          stars: '★★★★★',
          difficulty: '7/10 Difficulty',
          excerpt: 'Robert Trent Jones Jr. at his most scenic. The lighthouse remains visible for most of the round and the setting is one of the prettiest in Spain.',
          img: '/images/alcanada.jpg',
          href: '/guides/alcanada-review',
        },
        {
          cls: 'course-card--3',
          badge: 'Best in Spain 2025',
          region: 'Son Vida · Palma',
          name: 'Son Muntaner',
          meta: ['DP World Tour', 'Par 72'],
          stars: '★★★★★',
          difficulty: '7/10 Difficulty',
          excerpt: 'Named Best Golf Course in Spain at the 2025 World Golf Awards, with Palma Bay views and a thousand-year-old olive tree on 15.',
          img: '/images/son-muntaner.webp',
          href: '/golf-courses#son-muntaner',
        },
        {
          cls: 'course-card--4',
          badge: null,
          region: 'Santa Ponsa · Southwest',
          name: 'Santa Ponsa 1',
          meta: ['DP World Tour host', 'Par 72', '€77-126'],
          stars: '★★★★☆',
          difficulty: '8/10 Difficulty',
          excerpt: 'Host of the 2021 DP World Tour Mallorca Open. Long, generous from the tee, and one of the easiest places on the island to swing freely with driver.',
          img: '/images/santa-ponsa.webp',
          href: '/guides/santa-ponsa-1-review',
        },
        {
          cls: 'course-card--5',
          badge: null,
          region: 'Camp de Mar · Southwest',
          name: 'Golf de Andratx',
          meta: ['Most challenging', 'Par 72', '€96-140'],
          stars: '★★★★☆',
          difficulty: '9/10 Difficulty',
          excerpt: 'The 6th is the longest par 5 in Spain at 609 metres. Built into coastal hills without compromise. Bring extra balls and no ego.',
          img: '/images/andratx.webp',
          href: '/golf-courses#golf-de-andratx',
        },
      ],
    },
    experience: {
      eyebrow: 'The experience',
      title: 'Most golf days in Mallorca are a tee time and a wave goodbye.',
      paragraphs: [
        'I spent over a decade coaching in China, where clients expected genuine improvement, not empty encouragement. Before that I coached at Pebble Beach, The Open Championship, and Evian.',
        "That background shapes every round I host. We play one of Mallorca's best courses together, and the coaching arrives where it matters: on the tee, into the wind, around the greens, and over the shots that usually cost people the score they wanted.",
        'Everything is arranged before you arrive: course, tee time, and lunch. Your only job on the day is to play.',
      ],
      button: 'See the Experiences',
      features: [
        {
          title: 'Everything arranged',
          text: 'Course, tee time, transport, and lunch handled before you arrive.',
        },
        {
          title: 'On-course coaching',
          text: 'Useful observations in the middle of a round, when they can still change something.',
        },
        {
          title: 'Completely private',
          text: 'Just you and a PGA Advanced Professional. No strangers in your group.',
        },
        {
          title: 'Access to more',
          text: 'Members-only courses that most visiting golfers cannot book by themselves.',
        },
      ],
    },
    quote: {
      text: "After just 18 holes together, I've discovered a new ceiling to my potential.",
      attribution: 'Jo, after a day at Son Gual',
    },
    winners: {
      eyebrow: 'Proof of work',
      title: 'Competition winners, ambitious golfers, and plenty in between.',
      intro: 'I have coached elite juniors, club golfers, and plenty of people who simply wanted to stop throwing shots away. The common thread is usually the same: clearer decisions, better patterns, and improvement that still shows up when the card is in your hand.',
      testimonial:
        "I've been playing golf since I was five. I figured I had the fundamentals down and just needed more reps, not a coach. Then someone gifted me a lesson with Andy, and I decided to give it a shot. I'm glad I did. We worked through the finer details of my swing, focused on solid ball contact, better weight transfer, and mechanics. Even the smallest tweaks produced consistent results, and I'm confident they'll shave 5-10 strokes off my game from just one session. Andy was a total pro. Can't thank him enough.",
      attribution: 'Adam',
    },
    packages: {
      eyebrow: 'Experiences & Packages',
      title: 'Three ways to spend the day.',
      intro: 'All three are private, and all three are hosted by me. The difference is how much of the day you want arranged around the golf.',
      items: [
        {
          tier: 'The Mallorca Round',
          name: 'Play with a Pro',
          features: [
            'Course matched to your game and handicap',
            'Tee time secured and fully handled',
            'Pre-round briefing and warm-up',
            '18 holes alongside Andy',
            'On-course coaching throughout',
            'Post-round debrief - honest and clear',
          ],
          price: '€350 pp + green fee',
          note: 'Green fees are additional - typically €80-220 pp depending on course and season.',
          cta: 'Enquire',
        },
        {
          tier: 'The Signature Day',
          name: 'Hosted Golf Day',
          featured: true,
          features: [
            'Everything in The Mallorca Round',
            "Son Gual or Alcanada - two of the island's finest",
            'Long lunch at the course restaurant',
            'Curated surprise gift',
            'Unhurried pace - a full day, not a rushed round',
          ],
          price: 'From €450 pp + green fee',
          note: 'Green fees are additional - typically €80-220 pp depending on course and season.',
          cta: 'Enquire',
        },
        {
          tier: 'The Full Experience',
          name: 'Bespoke Golf Journey',
          features: [
            'Multi-course day or full 4-day itinerary',
            'Private transport from Palma hotels or villas',
            'Dinner at a handpicked Mallorca restaurant',
            'Spa or recovery session at a partner venue',
            'Sunset coastal drive along the Tramuntana',
            'Hot air balloon over the mountains',
            'Wine tasting at a Mallorcan vineyard',
            'Full concierge for groups and corporates',
          ],
          price: 'Custom itinerary - on enquiry',
          cta: 'Enquire',
        },
      ],
    },
    faq: {
      eyebrow: 'Questions',
      title: 'Things people ask before getting in touch.',
      intro: "Tell me your dates, your handicap, and what you're looking for. I come back personally, usually sooner, always within 24 hours.",
      items: [
        {
          q: 'Do I need to be a good golfer?',
          a: 'Not at all. The experience adjusts to your game: beginners and scratch players both get something from the day. The only requirement is wanting a golf day that feels more personal than a standard tee time.',
        },
        {
          q: 'Which course do you use?',
          a: "It depends on you. Son Gual and Alcanada are my primary venues for a serious full day. For beginners, groups, or shorter rounds, there are better options, and I'll tell you honestly which one fits.",
        },
        {
          q: 'How do I book?',
          a: "Get in touch. Tell me your dates and what you're looking for, and I come back personally within 24 hours. No booking systems. No waiting.",
        },
        {
          q: 'Is this suitable for a group?',
          a: 'Yes. The experiences work for solos, pairs, groups of friends, and corporate days. The Full Experience is particularly popular for business groups and executives visiting the island.',
        },
        {
          q: 'When is the best time of year to visit?',
          a: 'October, November, March, and April. Best combination of course conditions, weather, value, and pace of play. The island is playable year-round: in January the fairways here are better than August fairways in England.',
        },
      ],
    },
    finalCta: {
      eyebrow: 'Ready to play Mallorca properly?',
      title: "Get in touch. I'll sort the rest.",
      body: "Tell me your dates, your handicap, and what you want from the day. I'll come back with a recommendation personally within 24 hours.",
      quote: "You'll play better golf, and you'll know why.",
      primaryCta: 'Book Your Day',
      secondaryCta: 'WhatsApp',
    },
  },
}

function deepMerge(base, override) {
  if (Array.isArray(base) || Array.isArray(override)) {
    return override ?? base
  }
  if (base && typeof base === 'object' && override && typeof override === 'object') {
    const output = { ...base }
    for (const key of Object.keys(override)) {
      output[key] = deepMerge(base[key], override[key])
    }
    return output
  }
  return override ?? base
}

const HOME_OVERRIDES = {
  de: {
    hero: {
      eyebrow: 'PGA Advanced Professional · Mallorca',
      titleLines: ['Spielen Sie Mallorcas', 'beste Plätze.'],
      emphasis: 'Mit einem Profi an Ihrer Seite.',
      primaryCta: 'Tag buchen',
      secondaryCta: 'Plätze ansehen',
    },
    intro: {
      eyebrow: 'Was den Unterschied macht',
      title: 'Die meisten Golftage auf Mallorca beginnen auf einer Buchungsplattform und enden mit einer Rechnung. Hier ist es persönlicher.',
      body: 'Ich begleite private Golftage auf den besten Plätzen der Insel. Das Coaching passiert während der Runde und nicht erst danach als Zusatz. Das Golf ist besser, die Entscheidungen werden klarer und der ganze Tag fühlt sich wirklich gut betreut an.',
      stats: [
        { value: '18', label: 'Jahre Golf-Coaching' },
        { value: '15.000+', label: 'Coachings durchgeführt' },
        { value: '300+', label: 'Turniersieger betreut' },
      ],
    },
    socialProof: 'Andy 教练 · Über 300 Millionen Aufrufe seiner Golf-Coaching-Videos auf TikTok · Coaching-Inhalte, denen man weltweit vertraut',
    how: {
      eyebrow: 'So funktioniert es',
      title: 'Drei einfache Schritte.',
      steps: [
        { number: '01', title: 'Schreiben Sie mir', text: 'Nennen Sie mir Ihre Termine, Ihr Handicap und wonach Sie suchen. Ich antworte persönlich innerhalb von 24 Stunden.' },
        { number: '02', title: 'Ich plane den Tag', text: 'Platzempfehlung, Abschlagszeit, Mittagessen und Transport stehen fest, bevor Sie ankommen.' },
        { number: '03', title: 'Ankommen und spielen', text: 'Ihre Aufgabe ist es nur, die Runde zu genießen. Die meisten spielen besser, als sie erwartet haben.' },
      ],
    },
    whyMallorca: {
      eyebrow: 'Warum Mallorca',
      title: 'Mallorca hat Plätze auf Tour-Niveau. Viele Besucher spielen zwei oder drei und entdecken den Rest nie.',
      paragraphs: [
        'Viele der besten Plätze Europas schließen im Winter. Mallorca nicht. Oktober bis April ist die beste Zeit: niedrigere Greenfees, ruhigere Plätze und Bedingungen, die anderswo selbst im Sommer selten sind.',
        '22 Plätze liegen in Reichweite, mehrere mit echter Tour-Geschichte und ernsthafter Architektur. Mallorca ist ein richtiges Golfziel, und die meisten Besucher kratzen nur an der Oberfläche.',
      ],
      stats: [
        { value: '22', label: 'Plätze auf der Insel' },
        { value: '300+', label: 'Sonnentage pro Jahr' },
        { value: 'Jan-Dez', label: 'ganzjährige Saison' },
        { value: '€80-220', label: 'Greenfee-Bereich' },
      ],
    },
    courses: { eyebrow: 'Ausgewählte Plätze', title: 'Mallorcas beste Plätze, gespielt und ehrlich bewertet.', viewAll: 'Alle 22 Plätze ansehen →' },
    experience: {
      eyebrow: 'Das Erlebnis',
      title: 'Die meisten Golftage auf Mallorca sind eine Abschlagszeit und ein kurzes Winken zum Abschied.',
      paragraphs: [
        'Ich habe über ein Jahrzehnt in China gecoacht, wo Kunden echte Verbesserung erwarten und keine leeren Floskeln.',
        'Dieser Hintergrund prägt jede Runde, die ich begleite. Wir spielen einen der besten Plätze Mallorcas zusammen, und das Coaching kommt dort, wo es etwas verändert: am Abschlag, in den Wind, rund ums Grün und bei den Entscheidungen, die Schläge kosten.',
        'Alles ist geregelt, bevor Sie ankommen: Platz, Abschlagszeit und Mittagessen. Ihre einzige Aufgabe ist es, zu spielen.',
      ],
      button: 'Erlebnisse ansehen',
      features: [
        { title: 'Alles organisiert', text: 'Platz, Abschlagszeit, Transport und Mittagessen stehen vor Ihrer Ankunft fest.' },
        { title: 'On-Course-Coaching', text: 'Hilfreiche Beobachtungen mitten in der Runde, wenn sie noch etwas verändern können.' },
        { title: 'Komplett privat', text: 'Nur Sie und ein PGA Advanced Professional. Keine Fremden in Ihrer Gruppe.' },
        { title: 'Mehr Zugang', text: 'Mitgliederplätze, die die meisten Besucher nicht selbst buchen können.' },
      ],
    },
    quote: { text: 'Nach nur 18 Löchern zusammen habe ich eine neue Grenze meines Potenzials entdeckt.', attribution: 'Jo, nach einem Tag in Son Gual' },
    winners: {
      eyebrow: 'Belege der Arbeit',
      title: 'Turniersieger, ambitionierte Golfer und viele dazwischen.',
      intro: 'Ich habe Elite-Junioren, Clubgolfer und viele Menschen gecoacht, die einfach aufhören wollten, Schläge unnötig wegzuwerfen. Die Gemeinsamkeit ist fast immer dieselbe: klarere Entscheidungen, bessere Muster und Fortschritt, der auch unter Druck bestehen bleibt.',
      testimonial: 'Ich spiele seit meinem fünften Lebensjahr Golf. Ich dachte, ich bräuchte nur mehr Wiederholungen, keinen Coach. Dann bekam ich eine Stunde mit Andy geschenkt und habe sie ausprobiert. Es hat sich gelohnt. Kleine Anpassungen führten sofort zu konstant besseren Treffern und echtem Fortschritt.',
      attribution: 'Adam',
    },
    packages: {
      eyebrow: 'Erlebnisse und Pakete',
      title: 'Drei Arten, den Tag zu verbringen.',
      intro: 'Alle drei sind privat, und alle drei begleite ich persönlich. Der Unterschied liegt darin, wie viel des Tages Sie rund um das Golf arrangiert haben möchten.',
      items: [
        {
          tier: 'Die Mallorca-Runde',
          name: 'Spielen mit einem Pro',
          features: [
            'Platz passend zu Ihrem Spiel und Ihrem Handicap',
            'Abschlagszeit gesichert und vollständig organisiert',
            'Briefing und Aufwärmen vor der Runde',
            '18 Löcher an Andys Seite',
            'Coaching während der gesamten Runde',
            'Nachbesprechung danach, ehrlich und klar',
          ],
          price: '€350 p. P. + Greenfee',
          note: 'Greenfees kommen zusätzlich dazu. Je nach Platz und Saison meist zwischen €80 und €220 pro Person.',
          cta: 'Anfragen',
        },
        {
          tier: 'Der Signature Day',
          name: 'Begleiteter Golftag',
          featured: true,
          features: [
            'Alles aus der Mallorca-Runde',
            'Son Gual oder Alcanada, zwei der besten Plätze der Insel',
            'Langes Mittagessen im Clubrestaurant',
            'Kuratiertes Überraschungsgeschenk',
            'Entspanntes Tempo, ein voller Tag ohne Hektik',
          ],
          price: 'Ab €450 p. P. + Greenfee',
          note: 'Greenfees kommen zusätzlich dazu. Je nach Platz und Saison meist zwischen €80 und €220 pro Person.',
          cta: 'Anfragen',
        },
        {
          tier: 'Das komplette Erlebnis',
          name: 'Individuelle Golfreise',
          features: [
            'Mehrplatz-Tag oder kompletter 4-Tage-Plan',
            'Privater Transport von Hotels oder Villen in Palma',
            'Abendessen in einem ausgewählten Restaurant',
            'Spa- oder Recovery-Session bei einem Partner',
            'Sonnenuntergangsfahrt durch die Tramuntana',
            'Heißluftballon über den Bergen',
            'Weinprobe auf einem mallorquinischen Weingut',
            'Concierge-Organisation für Gruppen und Firmen',
          ],
          price: 'Individuelle Planung auf Anfrage',
          cta: 'Anfragen',
        },
      ],
    },
    faq: {
      eyebrow: 'Fragen',
      title: 'Dinge, die man fragt, bevor man sich meldet.',
      intro: 'Nennen Sie mir Ihre Termine, Ihr Handicap und wonach Sie suchen. Ich antworte persönlich innerhalb von 24 Stunden.',
      items: [
        { q: 'Muss ich ein guter Golfer sein?', a: 'Überhaupt nicht. Das Erlebnis passt sich Ihrem Spiel an. Anfänger und Scratch-Spieler profitieren beide.' },
        { q: 'Welchen Platz nutzen Sie?', a: 'Das hängt von Ihnen ab. Son Gual und Alcanada sind meine Hauptplätze für einen ernsthaften vollen Tag, aber nicht immer die richtige Wahl.' },
        { q: 'Wie buche ich?', a: 'Schreiben Sie mir einfach. Keine Buchungsplattformen. Keine Warteschleife.' },
        { q: 'Ist das für Gruppen geeignet?', a: 'Ja. Für Einzelpersonen, Paare, Freundesgruppen und Firmenrunden.' },
        { q: 'Wann ist die beste Jahreszeit?', a: 'Oktober, November, März und April. Die beste Mischung aus Platzbedingungen, Wetter, Wert und Spielfluss.' },
      ],
    },
    finalCta: {
      eyebrow: 'Bereit, Mallorca richtig zu spielen?',
      title: 'Melden Sie sich. Ich kümmere mich um den Rest.',
      body: 'Nennen Sie mir Ihre Termine, Ihr Handicap und was Sie sich vom Tag wünschen. Ich melde mich persönlich innerhalb von 24 Stunden mit einer Empfehlung.',
      quote: 'Sie werden besseres Golf spielen und verstehen, warum.',
      primaryCta: 'Tag buchen',
      secondaryCta: 'WhatsApp',
    },
  },
  es: {
    hero: {
      eyebrow: 'PGA Advanced Professional · Mallorca',
      titleLines: ['Juega los mejores', 'campos de Mallorca.'],
      emphasis: 'Con un profesional a tu lado.',
      primaryCta: 'Reserva tu día',
      secondaryCta: 'Explorar campos',
      trust: [
        'PGA Advanced Professional',
        'Trackman Master Certified',
        '18 años dedicados al coaching de golf',
        'Pebble Beach · Évian · The Open',
      ],
    },
    intro: {
      eyebrow: 'Qué marca la diferencia',
      title: 'Muchos días de golf en Mallorca empiezan con una plataforma de reservas y acaban con una factura. Esto es más personal.',
      body: 'Organizo días privados de golf en algunos de los mejores campos de la isla, con el coaching integrado en la vuelta y no como un extra al final. Se juega mejor, se toman decisiones más claras y todo el día se siente mejor llevado.',
      stats: [
        { value: '18', label: 'años dedicados al coaching de golf' },
        { value: '15.000+', label: 'lecciones impartidas' },
        { value: '300+', label: 'ganadores de competición entrenados' },
      ],
    },
    socialProof: 'Andy 教练 · Más de 300 millones de visualizaciones de sus vídeos de coaching de golf en TikTok · Contenido de coaching seguido en todo el mundo',
    how: {
      eyebrow: 'Cómo funciona',
      title: 'Tres pasos sencillos.',
      steps: [
        { number: '01', title: 'Escríbame', text: 'Dígame sus fechas, su hándicap y lo que busca. Le respondo personalmente en 24 horas.' },
        { number: '02', title: 'Yo construyo el día', text: 'La recomendación de campo, el tee time, el almuerzo y el transporte quedan resueltos antes de llegar.' },
        { number: '03', title: 'Llegue y juegue', text: 'Su trabajo es disfrutar la vuelta. La mayoría juega mejor de lo esperado.' },
      ],
    },
    whyMallorca: {
      eyebrow: 'Por qué Mallorca',
      title: 'Mallorca tiene campos de nivel Tour. Muchos visitantes juegan unos pocos y nunca descubren el resto.',
      paragraphs: [
        'Muchos de los mejores campos de Europa cierran en invierno. Mallorca no. De octubre a abril está el punto dulce: green fees más bajos, campos más tranquilos y unas condiciones que en otros lugares serían una ronda de verano.',
        'Hay 22 campos a poca distancia, varios con historia de Tour y una arquitectura seria. Mallorca es un destino de golf de verdad, y la mayoría de los visitantes apenas rascan la superficie.',
      ],
      stats: [
        { value: '22', label: 'campos en la isla' },
        { value: '300+', label: 'días de sol al año' },
        { value: 'Ene-Dic', label: 'temporada todo el año' },
        { value: '€80-220', label: 'rango de green fees' },
      ],
    },
    courses: {
      eyebrow: 'Campos destacados',
      title: 'Los mejores de Mallorca, jugados y revisados.',
      viewAll: 'Ver los 22 campos →',
      items: [
        {
          cls: 'course-card--1',
          badge: 'Selección personal',
          region: 'Palma · 11 km del centro',
          name: 'Son Gual',
          meta: ['Championship', 'Par 72', '€80-165'],
          stars: '★★★★★',
          difficulty: 'Dificultad 9/10',
          excerpt:
            'El diseño de Thomas Himmel, de 2007, vive en su propio ecosistema de viento. El tramo final, del 15 al 18, está entre los mejores de Europa.',
          img: '/images/son-gual.jpg',
          href: '/guides/son-gual-review',
        },
        {
          cls: 'course-card--2',
          badge: 'Selección personal',
          region: 'Alcúdia · Norte de Mallorca',
          name: 'Alcanada',
          meta: ['Costa', 'Par 72', '€115-220'],
          stars: '★★★★★',
          difficulty: 'Dificultad 7/10',
          excerpt:
            'Robert Trent Jones Jr. en su versión más escénica. El faro acompaña casi toda la vuelta y el entorno es de los más bonitos de España.',
          img: '/images/alcanada.jpg',
          href: '/guides/alcanada-review',
        },
        {
          cls: 'course-card--3',
          badge: 'Mejor campo de España 2025',
          region: 'Son Vida · Palma',
          name: 'Son Muntaner',
          meta: ['DP World Tour', 'Par 72'],
          stars: '★★★★★',
          difficulty: 'Dificultad 7/10',
          excerpt:
            'Elegido mejor campo de golf de España en los World Golf Awards 2025, con vistas a la bahía de Palma y un olivo milenario en el hoyo 15.',
          img: '/images/son-muntaner.webp',
          href: '/golf-courses#son-muntaner',
        },
        {
          cls: 'course-card--4',
          badge: null,
          region: 'Santa Ponsa · Suroeste',
          name: 'Santa Ponsa 1',
          meta: ['Sede del DP World Tour', 'Par 72', '€77-126'],
          stars: '★★★★☆',
          difficulty: 'Dificultad 8/10',
          excerpt:
            'Sede del Mallorca Open de 2021. Largo, generoso desde el tee y uno de los mejores lugares de la isla para disfrutar pegando driver.',
          img: '/images/santa-ponsa.webp',
          href: '/guides/santa-ponsa-1-review',
        },
        {
          cls: 'course-card--5',
          badge: null,
          region: 'Camp de Mar · Suroeste',
          name: 'Golf de Andratx',
          meta: ['El reto más serio', 'Par 72', '€96-140'],
          stars: '★★★★☆',
          difficulty: 'Dificultad 9/10',
          excerpt:
            'El hoyo 6 es el par 5 más largo de España, con 609 metros. Construido en colinas costeras sin concesiones. Lleve bolas de sobra y deje el ego fuera.',
          img: '/images/andratx.webp',
          href: '/golf-courses#golf-de-andratx',
        },
      ],
    },
    experience: {
      eyebrow: 'La experiencia',
      title: 'Muchos días de golf en Mallorca son un tee time y un adiós.',
      paragraphs: [
        'Pasé más de una década enseñando en China, donde los clientes esperaban una mejora real y medible, no frases vacías.',
        'Ese bagaje marca cada vuelta que acompaño. Jugamos juntos uno de los mejores campos de Mallorca y el coaching aparece donde de verdad importa: en el tee, en el viento, alrededor del green y sobre los golpes que suelen costar la tarjeta.',
        'Todo está resuelto antes de llegar: campo, hora de salida y almuerzo. Su único trabajo ese día es jugar.',
      ],
      button: 'Ver experiencias',
      features: [
        {
          title: 'Todo organizado',
          text: 'Campo, tee time, transporte y almuerzo resueltos antes de que llegue.',
        },
        {
          title: 'Coaching en el campo',
          text: 'Observaciones útiles en mitad de la vuelta, cuando todavía pueden cambiar algo.',
        },
        {
          title: 'Completamente privado',
          text: 'Solo usted y un PGA Advanced Professional. Nadie más en el grupo.',
        },
        {
          title: 'Acceso a más',
          text: 'Campos de socios a los que la mayoría de los visitantes no puede acceder por su cuenta.',
        },
      ],
    },
    quote: {
      text: 'Después de solo 18 hoyos juntos, sentí que mi techo estaba más arriba de lo que pensaba.',
      attribution: 'Jo, después de un día en Son Gual',
    },
    winners: {
      eyebrow: 'Resultados',
      title: 'Ganadores de competición, golfistas ambiciosos y muchos perfiles intermedios.',
      intro:
        'He entrenado a juniors de élite, jugadores de club y a muchas personas que simplemente querían dejar de regalar golpes. El patrón suele ser el mismo: decisiones más claras, mejores rutinas y una mejora que sigue apareciendo cuando la tarjeta sí importa.',
      testimonial:
        'Juego al golf desde los cinco años. Pensaba que ya tenía la base hecha y que solo necesitaba más repeticiones, no un coach. Luego me regalaron una sesión con Andy y decidí probar. Menos mal. Afinamos detalles de mi swing, el contacto de bola, la transferencia de peso y la mecánica. Incluso cambios pequeños dieron resultados constantes, y estoy seguro de que me ahorrarán entre cinco y diez golpes. Andy fue un auténtico profesional. No puedo agradecérselo lo suficiente.',
      attribution: 'Adam',
    },
    packages: {
      eyebrow: 'Experiencias y paquetes',
      title: 'Tres maneras de pasar el día.',
      intro: 'Las tres opciones son privadas y las tres las llevo yo personalmente. La diferencia está en cuánto del día quiere organizar alrededor del golf.',
      items: [
        {
          tier: 'La vuelta Mallorca',
          name: 'Jugar con un Pro',
          features: [
            'Campo elegido según su juego y su hándicap',
            'Hora de salida asegurada y completamente gestionada',
            'Briefing y calentamiento antes de la vuelta',
            '18 hoyos junto a Andy',
            'Coaching durante toda la vuelta',
            'Debrief posterior, claro y honesto',
          ],
          price: '€350 p. p. + green fee',
          note: 'El green fee se añade aparte. Normalmente entre €80 y €220 por persona según el campo y la temporada.',
          cta: 'Consultar',
        },
        {
          tier: 'El Signature Day',
          name: 'Día de golf acompañado',
          featured: true,
          features: [
            'Todo lo incluido en La vuelta Mallorca',
            'Son Gual o Alcanada, dos de los mejores campos de la isla',
            'Almuerzo largo en el restaurante del club',
            'Regalo sorpresa seleccionado con criterio',
            'Ritmo relajado, un día completo, sin prisas',
          ],
          price: 'Desde €450 p. p. + green fee',
          note: 'El green fee se añade aparte. Normalmente entre €80 y €220 por persona según el campo y la temporada.',
          cta: 'Consultar',
        },
        {
          tier: 'La experiencia completa',
          name: 'Viaje de golf a medida',
          features: [
            'Día multi-campo o itinerario completo de 4 días',
            'Transporte privado desde hoteles o villas en Palma',
            'Cena en un restaurante seleccionado',
            'Sesión de spa o recuperación en un partner',
            'Ruta al atardecer por la Tramuntana',
            'Paseo en globo sobre la sierra',
            'Cata de vinos en una finca mallorquina',
            'Coordinación concierge para grupos y empresa',
          ],
          price: 'Itinerario a medida, bajo consulta',
          cta: 'Consultar',
        },
      ],
    },
    faq: {
      eyebrow: 'Preguntas',
      title: 'Lo que suelen preguntar antes de escribir.',
      intro: 'Dígame sus fechas, su hándicap y lo que busca. Le responderé personalmente en 24 horas.',
      items: [
        {
          q: '¿Hace falta jugar bien?',
          a: 'No. La experiencia se adapta a su nivel. Tanto un principiante como un jugador de scratch pueden sacar mucho del día. Lo único importante es querer algo más personal que un tee time estándar.',
        },
        {
          q: '¿Qué campo utiliza?',
          a: 'Depende de usted. Son Gual y Alcanada son mis sedes principales para un día serio y completo, pero no siempre son la mejor opción. Si viene en grupo, con principiantes o quiere algo más corto, le diré con honestidad qué encaja mejor.',
        },
        {
          q: '¿Cómo se reserva?',
          a: 'Escríbame. Dígame sus fechas y lo que busca, y le contestaré personalmente en 24 horas. Sin plataforma de reservas. Sin esperas.',
        },
        {
          q: '¿Sirve para grupos?',
          a: 'Sí. Funciona para una persona, para parejas, para grupos de amigos y para días corporativos. La experiencia completa encaja especialmente bien con grupos de empresa y directivos que visitan la isla.',
        },
        {
          q: '¿Cuál es la mejor época del año?',
          a: 'Octubre, noviembre, marzo y abril. Es la mejor combinación de estado del campo, clima, precio y ritmo de juego. La isla se juega todo el año: en enero los fairways aquí están mejor que muchos fairways ingleses en agosto.',
        },
      ],
    },
    finalCta: {
      eyebrow: '¿Listo para jugar Mallorca de verdad?',
      title: 'Escríbame. Yo me encargo del resto.',
      body: 'Dígame sus fechas, su hándicap y lo que quiere del día. Le responderé personalmente en 24 horas.',
      quote: 'Jugará mejor y entenderá por qué.',
      primaryCta: 'Reserva tu día',
      secondaryCta: 'WhatsApp',
    },
  },
  fr: {
    hero: { eyebrow: 'PGA Advanced Professional · Majorque', titleLines: ['Jouez les plus beaux', 'parcours de Majorque.'], emphasis: 'Avec un pro à vos côtés.', primaryCta: 'Réserver votre journée', secondaryCta: 'Voir les parcours' },
    intro: {
      eyebrow: 'Ce qui fait la différence',
      title: 'Beaucoup de journées de golf à Majorque commencent sur une plateforme de réservation et se terminent avec une facture. Ici, c’est plus personnel.',
      body: 'J’organise des journées de golf privées sur les meilleurs parcours de l’île, avec le coaching intégré pendant la partie plutôt qu’ajouté après. On joue mieux, les décisions deviennent plus claires et toute la journée est mieux tenue.',
      stats: [
        { value: '18', label: 'années consacrées au coaching golf' },
        { value: '15 000+', label: 'leçons données' },
        { value: '300+', label: 'vainqueurs de compétition accompagnés' },
      ],
    },
    socialProof: 'Andy 教练 · Plus de 300 millions de vues pour ses vidéos de coaching golf sur TikTok · Un contenu de coaching suivi dans le monde entier',
    how: { eyebrow: 'Comment cela fonctionne', title: 'Trois étapes simples.', steps: [{ number: '01', title: 'Écrivez-moi', text: 'Donnez-moi vos dates, votre handicap et ce que vous cherchez. Je réponds personnellement sous 24 heures.' }, { number: '02', title: 'Je construis votre journée', text: 'Parcours, heure de départ, déjeuner et transport sont réglés avant votre arrivée.' }, { number: '03', title: 'Arrivez et jouez', text: 'Votre seul travail est de profiter du tour. La plupart jouent mieux qu’ils ne l’imaginaient.' }] },
    whyMallorca: { eyebrow: 'Pourquoi Majorque', title: 'Majorque a des parcours de niveau Tour. Beaucoup de visiteurs n’en voient qu’une petite partie.', paragraphs: ['Beaucoup des meilleurs parcours d’Europe ferment l’hiver. Majorque, non. D’octobre à avril, vous profitez de green fees plus doux, de parcours plus calmes et de conditions qui feraient envie à bien des destinations estivales.', 'Vingt-deux parcours sont accessibles en peu de temps, plusieurs avec une vraie histoire de Tour et une architecture sérieuse. Majorque est une vraie destination de golf, et la plupart des visiteurs n’en voient qu’une petite partie.'], stats: [{ value: '22', label: 'parcours sur l’île' }, { value: '300+', label: 'jours de soleil par an' }, { value: 'Jan-Dec', label: 'saison toute l’année' }, { value: '€80-220', label: 'fourchette de green fees' }] },
    courses: { eyebrow: 'Parcours en vedette', title: 'Les meilleurs parcours de Majorque, joués et évalués honnêtement.', viewAll: 'Voir les 22 parcours →' },
    experience: {
      eyebrow: 'L’expérience',
      title: 'La plupart des journées de golf à Majorque se limitent à une heure de départ et un signe de la main.',
      paragraphs: ['J’ai passé plus de dix ans à coacher en Chine, dans un contexte où l’on attendait une vraie amélioration, pas des encouragements creux.', 'Cette expérience façonne chaque partie que j’accompagne. Nous jouons ensemble sur l’un des meilleurs parcours de Majorque, et le coaching arrive là où il fait gagner des coups.', 'Tout est réglé avant votre arrivée : parcours, heure de départ et déjeuner. Votre seul travail ce jour-là est de jouer.'],
      button: 'Voir les expériences',
      features: [
        { title: 'Tout est organisé', text: 'Parcours, heure de départ, transport et déjeuner sont réglés avant votre arrivée.' },
        { title: 'Coaching sur le parcours', text: 'Des observations utiles au bon moment, tant qu’elles peuvent encore changer quelque chose.' },
        { title: 'Entièrement privé', text: 'Juste vous et un PGA Advanced Professional. Personne d’autre dans votre partie.' },
        { title: 'Accès à davantage', text: 'Des parcours membres que la plupart des visiteurs ne peuvent pas réserver seuls.' },
      ],
    },
    packages: {
      eyebrow: 'Expériences et forfaits',
      title: 'Trois façons de vivre la journée.',
      intro: 'Les trois options sont privées, et les trois sont menées par moi. La différence tient à ce que vous voulez organiser autour du golf.',
      items: [
        {
          tier: 'Le tour Mallorca',
          name: 'Jouer avec un Pro',
          features: [
            'Parcours choisi selon votre niveau et votre handicap',
            'Heure de départ réservée et entièrement gérée',
            'Briefing et échauffement avant la partie',
            '18 trous aux côtés d’Andy',
            'Coaching pendant toute la partie',
            'Débrief après la partie, honnête et clair',
          ],
          price: '350 € p. p. + green fee',
          note: 'Les green fees s’ajoutent à part. Comptez généralement entre 80 € et 220 € par personne selon le parcours et la saison.',
          cta: 'Demander',
        },
        {
          tier: 'La Signature Day',
          name: 'Journée de golf accompagnée',
          featured: true,
          features: [
            'Tout ce qui est inclus dans Le tour Mallorca',
            'Son Gual ou Alcanada, deux des meilleurs parcours de l’île',
            'Long déjeuner au restaurant du club',
            'Cadeau surprise choisi avec goût',
            'Un rythme détendu, une vraie journée complète',
          ],
          price: 'À partir de 450 € p. p. + green fee',
          note: 'Les green fees s’ajoutent à part. Comptez généralement entre 80 € et 220 € par personne selon le parcours et la saison.',
          cta: 'Demander',
        },
        {
          tier: 'L’expérience complète',
          name: 'Voyage de golf sur mesure',
          features: [
            'Journée multi-parcours ou itinéraire complet de 4 jours',
            'Transport privé depuis Palma, hôtel ou villa',
            'Dîner dans un restaurant sélectionné',
            'Session spa ou récupération chez un partenaire',
            'Route côtière au coucher du soleil dans la Tramuntana',
            'Vol en montgolfière au-dessus des montagnes',
            'Dégustation dans un domaine viticole majorquin',
            'Organisation concierge pour groupes et entreprises',
          ],
          price: 'Itinéraire sur mesure, sur demande',
          cta: 'Demander',
        },
      ],
    },
    faq: {
      eyebrow: 'Questions fréquentes',
      title: 'Ce que les gens demandent avant de prendre contact.',
      intro: 'Donnez-moi vos dates, votre handicap et ce que vous cherchez. Je réponds personnellement sous 24 heures.',
      items: [
        { q: 'Faut-il être un bon joueur ?', a: 'Pas du tout. L’expérience s’adapte à votre niveau. Débutants comme joueurs scratch peuvent y gagner quelque chose.' },
        { q: 'Quel parcours utilisez-vous ?', a: 'Cela dépend de vous. Son Gual et Alcanada sont mes principales bases pour une vraie grande journée, mais ce ne sont pas toujours les meilleurs choix.' },
        { q: 'Comment réserver ?', a: 'Écrivez-moi simplement. Donnez-moi vos dates et ce que vous cherchez, et je vous répondrai personnellement sous 24 heures. Pas de plateforme de réservation. Pas d’attente.' },
        { q: 'Est-ce adapté aux groupes ?', a: 'Oui. Pour une personne seule, un couple, un groupe d’amis ou une journée d’entreprise.' },
        { q: 'Quelle est la meilleure période ?', a: 'Octobre, novembre, mars et avril. C’est le meilleur mélange de conditions, météo, valeur et rythme de jeu.' },
      ],
    },
    finalCta: { eyebrow: 'Prêt à jouer Majorque comme il faut ?', title: 'Contactez-moi. Je m’occupe du reste.', body: 'Donnez-moi vos dates, votre handicap et ce que vous attendez de la journée. Je reviens vers vous personnellement sous 24 heures.', primaryCta: 'Réserver votre journée', secondaryCta: 'WhatsApp' },
  },
  nl: {
    hero: { eyebrow: 'PGA Advanced Professional · Mallorca', titleLines: ['Speel de beste', 'banen van Mallorca.'], emphasis: 'Met een professional aan uw zijde.', primaryCta: 'Boek uw dag', secondaryCta: 'Bekijk de banen' },
    intro: {
      eyebrow: 'Wat dit anders maakt',
      title: 'De meeste golfdagen op Mallorca beginnen op een boekingsplatform en eindigen met een rekening. Dit is persoonlijker.',
      body: 'Ik organiseer privé-golfdagen op de beste banen van het eiland, met coaching tijdens de ronde in plaats van als extra achteraf. U speelt beter, beslissingen worden duidelijker en de hele dag voelt beter verzorgd.',
      stats: [
        { value: '18', label: 'jaar golfcoaching' },
        { value: '15.000+', label: 'gegeven lessen' },
        { value: '300+', label: 'begeleide wedstrijdwinnaars' },
      ],
    },
    socialProof: 'Andy 教练 · Meer dan 300 miljoen views van zijn golfcoachingvideo’s op TikTok · Coachingcontent met wereldwijd vertrouwen',
    how: { eyebrow: 'Hoe het werkt', title: 'Drie eenvoudige stappen.', steps: [{ number: '01', title: 'Neem contact op', text: 'Vertel me uw data, handicap en wat u zoekt. Ik reageer persoonlijk binnen 24 uur.' }, { number: '02', title: 'Ik bouw uw dag', text: 'Baanadvies, tee time, lunch en vervoer worden geregeld vóór uw aankomst.' }, { number: '03', title: 'Kom en speel', text: 'Uw taak is simpel: genieten van de ronde. De meeste mensen spelen beter dan verwacht.' }] },
    whyMallorca: { eyebrow: 'Waarom Mallorca', title: 'Mallorca heeft banen op Tour-niveau. Veel bezoekers ontdekken maar een klein deel.', paragraphs: ['Veel van Europa’s beste banen sluiten in de winter. Mallorca niet. Van oktober tot april krijgt u lagere greenfees, rustigere banen en omstandigheden die elders midden in de zomer al goed zouden zijn.', 'Er liggen 22 banen binnen bereik, verschillende met echte Tourgeschiedenis en serieuze architectuur. Mallorca is een echte golfbestemming, en de meeste bezoekers zien daar maar een klein deel van.'], stats: [{ value: '22', label: 'banen op het eiland' }, { value: '300+', label: 'dagen zon per jaar' }, { value: 'Jan-Dec', label: 'seizoen het hele jaar' }, { value: '€80-220', label: 'greenfee-range' }] },
    courses: { eyebrow: 'Uitgelichte banen', title: 'De beste van Mallorca, gespeeld en eerlijk beoordeeld.', viewAll: 'Bekijk alle 22 banen →' },
    experience: {
      eyebrow: 'De ervaring',
      title: 'De meeste golfdagen op Mallorca zijn een tee time en een handdruk op de 18e.',
      paragraphs: ['Ik heb meer dan tien jaar in China gecoacht, waar klanten echte verbetering verwachtten in plaats van vage aanmoedigingen.', 'Die achtergrond bepaalt elke ronde die ik begeleid. We spelen samen op een van de beste banen van Mallorca en de coaching komt precies op de momenten waarop die echt iets verandert.', 'Alles is geregeld vóór uw aankomst: baan, starttijd en lunch. Uw enige taak is spelen.'],
      button: 'Bekijk de ervaringen',
      features: [
        { title: 'Alles geregeld', text: 'Baan, tee time, vervoer en lunch staan vast vóór uw aankomst.' },
        { title: 'Coaching op de baan', text: 'Nuttige observaties midden in de ronde, zolang ze nog iets kunnen veranderen.' },
        { title: 'Volledig privé', text: 'Alleen u en een PGA Advanced Professional. Geen onbekenden in uw flight.' },
        { title: 'Toegang tot meer', text: 'Ledenbanen die de meeste bezoekers niet zelfstandig kunnen boeken.' },
      ],
    },
    packages: {
      eyebrow: 'Ervaringen en pakketten',
      title: 'Drie manieren om de dag door te brengen.',
      intro: 'Alle drie zijn privé en alle drie worden persoonlijk door mij begeleid. Het verschil zit in hoeveel u rond het golf wilt laten regelen.',
      items: [
        {
          tier: 'De Mallorca-ronde',
          name: 'Spelen met een Pro',
          features: [
            'Baan gekozen op basis van uw spel en handicap',
            'Tee time vastgelegd en volledig geregeld',
            'Briefing en warming-up vóór de ronde',
            '18 holes samen met Andy',
            'Coaching gedurende de hele ronde',
            'Nabespreking achteraf, eerlijk en duidelijk',
          ],
          price: '€350 p.p. + greenfee',
          note: 'Greenfees komen daar nog bij. Reken meestal op €80 tot €220 per persoon, afhankelijk van baan en seizoen.',
          cta: 'Aanvragen',
        },
        {
          tier: 'De Signature Day',
          name: 'Begeleide golfdag',
          featured: true,
          features: [
            'Alles uit De Mallorca-ronde',
            'Son Gual of Alcanada, twee van de beste banen van het eiland',
            'Uitgebreide lunch in het clubrestaurant',
            'Een zorgvuldig gekozen verrassingscadeau',
            'Een ontspannen tempo, een volle dag zonder haast',
          ],
          price: 'Vanaf €450 p.p. + greenfee',
          note: 'Greenfees komen daar nog bij. Reken meestal op €80 tot €220 per persoon, afhankelijk van baan en seizoen.',
          cta: 'Aanvragen',
        },
        {
          tier: 'De volledige ervaring',
          name: 'Golfreis op maat',
          features: [
            'Dag over meerdere banen of volledige 4-daagse planning',
            'Privévervoer vanaf hotels of villa’s in Palma',
            'Diner in een zorgvuldig gekozen restaurant',
            'Spa- of herstelmoment bij een partnerlocatie',
            'Kustrit bij zonsondergang door de Tramuntana',
            'Luchtballonvaart boven de bergen',
            'Wijnproeverij op een Mallorcaanse wijngaard',
            'Concierge-regeling voor groepen en bedrijven',
          ],
          price: 'Maatwerkroute op aanvraag',
          cta: 'Aanvragen',
        },
      ],
    },
    faq: {
      eyebrow: 'Vragen',
      title: 'Wat mensen meestal vragen voordat ze contact opnemen.',
      intro: 'Vertel me uw data, handicap en wat u zoekt. Ik reageer persoonlijk binnen 24 uur.',
      items: [
        { q: 'Moet ik een goede golfer zijn?', a: 'Nee. De ervaring past zich aan uw spel aan. Zowel beginners als scratchspelers halen er iets uit.' },
        { q: 'Welke baan gebruikt u?', a: 'Dat hangt van u af. Son Gual en Alcanada zijn mijn hoofdlocaties voor een serieuze volledige dag, maar niet altijd de juiste keuze.' },
        { q: 'Hoe boek ik?', a: 'Neem gewoon contact op. Vertel me uw data en wat u zoekt, en ik kom persoonlijk binnen 24 uur bij u terug. Geen boekingsplatform. Geen wachtrij.' },
        { q: 'Is dit geschikt voor groepen?', a: 'Ja. Voor solo’s, koppels, vriendengroepen en zakelijke dagen.' },
        { q: 'Wat is de beste tijd van het jaar?', a: 'Oktober, november, maart en april. De beste mix van baancondities, weer, waarde en speeltempo.' },
      ],
    },
    finalCta: { eyebrow: 'Klaar om Mallorca goed te spelen?', title: 'Neem contact op. Ik regel de rest.', body: 'Vertel me uw data, handicap en wat u uit de dag wilt halen. Ik kom persoonlijk binnen 24 uur bij u terug.', primaryCta: 'Boek uw dag', secondaryCta: 'WhatsApp' },
  },
  sv: {
    hero: { eyebrow: 'PGA Advanced Professional · Mallorca', titleLines: ['Spela Mallorcas', 'bästa banor.'], emphasis: 'Med ett proffs vid din sida.', primaryCta: 'Boka din dag', secondaryCta: 'Se banorna' },
    intro: {
      eyebrow: 'Det som gör skillnaden',
      title: 'De flesta golfdagar på Mallorca börjar via en bokningsplattform och slutar med en faktura. Det här är mer personligt.',
      body: 'Jag arrangerar privata golfdagar på öns bästa banor, med coachingen invävd i rundan i stället för lagd ovanpå efteråt. Spelet blir bättre, besluten blir tydligare och hela dagen känns mer omhändertagen.',
      stats: [
        { value: '18', label: 'år av golfcoaching' },
        { value: '15 000+', label: 'lektioner genomförda' },
        { value: '300+', label: 'tävlingsvinnare coachade' },
      ],
    },
    socialProof: 'Andy 教练 · Över 300 miljoner visningar av hans golfcoachingvideor på TikTok · Coachinginnehåll med globalt förtroende',
    how: { eyebrow: 'Så fungerar det', title: 'Tre enkla steg.', steps: [{ number: '01', title: 'Hör av dig', text: 'Berätta dina datum, ditt handicap och vad du letar efter. Jag svarar personligen inom 24 timmar.' }, { number: '02', title: 'Jag bygger dagen', text: 'Bana, starttid, lunch och transport ordnas innan du kommer.' }, { number: '03', title: 'Kom och spela', text: 'Din uppgift är att njuta av ronden. De flesta spelar bättre än de trodde.' }] },
    whyMallorca: { eyebrow: 'Varför Mallorca', title: 'Mallorca har banor på tournivå. Många besökare ser bara en liten del av dem.', paragraphs: ['Många av Europas bästa banor stänger under vintern. Mallorca gör det inte. Från oktober till april får du lägre greenfees, lugnare banor och förhållanden som många andra platser bara kan drömma om.', 'Det finns 22 banor inom räckhåll, flera med riktig Tour-historia och seriös design. Mallorca är en riktig golfdestination, och de flesta besökare ser bara en liten del av vad som finns här.'], stats: [{ value: '22', label: 'banor på ön' }, { value: '300+', label: 'soldagar per år' }, { value: 'Jan-Dec', label: 'säsong året runt' }, { value: '€80-220', label: 'greenfee-nivå' }] },
    courses: { eyebrow: 'Utvalda banor', title: 'Mallorcas bästa banor, spelade och ärligt recenserade.', viewAll: 'Se alla 22 banor →' },
    experience: {
      eyebrow: 'Upplevelsen',
      title: 'De flesta golfdagar på Mallorca är bara en starttid och ett handslag på 18:e.',
      paragraphs: ['Jag coachade i Kina i över ett decennium, där kunder förväntade sig verklig förbättring och inte tomma uppmuntringsord.', 'Den bakgrunden följer med i varje rond jag är värd för. Vi spelar tillsammans på en av Mallorcas bästa banor och coachingen kommer där den faktiskt gör skillnad.', 'Allt är ordnat innan du kommer: bana, starttid och lunch. Din enda uppgift den dagen är att spela.'],
      button: 'Se upplevelserna',
      features: [
        { title: 'Allt ordnat', text: 'Bana, starttid, transport och lunch är klara innan du anländer.' },
        { title: 'Coaching på banan', text: 'Användbara observationer mitt i rundan, medan de fortfarande kan förändra något.' },
        { title: 'Helt privat', text: 'Bara du och en PGA Advanced Professional. Inga främlingar i gruppen.' },
        { title: 'Tillgång till mer', text: 'Medlemsbanor som de flesta besökare inte kan boka själva.' },
      ],
    },
    packages: {
      eyebrow: 'Upplevelser och paket',
      title: 'Tre sätt att göra dagen.',
      intro: 'Alla tre är privata och alla tre leds personligen av mig. Skillnaden ligger i hur mycket av dagen du vill bygga runt golfen.',
      items: [
        {
          tier: 'Mallorca-rundan',
          name: 'Spela med ett proffs',
          features: [
            'Bana vald efter ditt spel och ditt handicap',
            'Starttid säkrad och helt ordnad',
            'Briefing och uppvärmning före rundan',
            '18 hål tillsammans med Andy',
            'Coaching genom hela rundan',
            'Genomgång efteråt, tydlig och ärlig',
          ],
          price: '€350 p.p. + greenfee',
          note: 'Greenfee tillkommer. Räkna oftast med mellan €80 och €220 per person beroende på bana och säsong.',
          cta: 'Skicka förfrågan',
        },
        {
          tier: 'Signature Day',
          name: 'Värdad golfdag',
          featured: true,
          features: [
            'Allt som ingår i Mallorca-rundan',
            'Son Gual eller Alcanada, två av öns bästa banor',
            'Lång lunch i klubbrestaurangen',
            'Noggrant utvald överraskningsgåva',
            'Lugnt tempo, en hel dag utan stress',
          ],
          price: 'Från €450 p.p. + greenfee',
          note: 'Greenfee tillkommer. Räkna oftast med mellan €80 och €220 per person beroende på bana och säsong.',
          cta: 'Skicka förfrågan',
        },
        {
          tier: 'Den fulla upplevelsen',
          name: 'Skräddarsydd golfresa',
          features: [
            'Dag på flera banor eller komplett 4-dagarsupplägg',
            'Privat transport från hotell eller villa i Palma',
            'Middag på noggrant utvald restaurang',
            'Spa- eller återhämtningspass hos partner',
            'Solnedgångstur genom Tramuntana',
            'Luftballong över bergen',
            'Vinprovning på mallorkinsk vingård',
            'Concierge-upplägg för grupper och företag',
          ],
          price: 'Skräddarsytt upplägg på förfrågan',
          cta: 'Skicka förfrågan',
        },
      ],
    },
    faq: {
      eyebrow: 'Frågor',
      title: 'Det folk brukar fråga innan de hör av sig.',
      intro: 'Berätta dina datum, ditt handicap och vad du letar efter. Jag svarar personligen inom 24 timmar.',
      items: [
        { q: 'Måste jag vara en bra golfare?', a: 'Nej. Upplevelsen anpassas efter ditt spel. Både nybörjare och scratchspelare får ut något av dagen.' },
        { q: 'Vilken bana använder du?', a: 'Det beror på dig. Son Gual och Alcanada är mina huvudval för en seriös heldag, men inte alltid rätt val.' },
        { q: 'Hur bokar jag?', a: 'Hör bara av dig. Berätta dina datum och vad du söker, så återkommer jag personligen inom 24 timmar. Ingen bokningsplattform. Ingen väntan.' },
        { q: 'Passar det här grupper?', a: 'Ja. För solo, par, kompisgäng och företagsdagar.' },
        { q: 'När är bästa tiden på året?', a: 'Oktober, november, mars och april. Den bästa kombinationen av banförhållanden, väder, värde och speltempo.' },
      ],
    },
    finalCta: { eyebrow: 'Redo att spela Mallorca på riktigt?', title: 'Hör av dig. Jag ordnar resten.', body: 'Berätta dina datum, ditt handicap och vad du vill få ut av dagen. Jag återkommer personligen inom 24 timmar.', primaryCta: 'Boka din dag', secondaryCta: 'WhatsApp' },
  },
  zh: {
    hero: { eyebrow: 'PGA Advanced Professional · Mallorca', titleLines: ['打马略卡最好的', '高尔夫球场。'], emphasis: '由职业教练全程陪同。', primaryCta: '预订这一天', secondaryCta: '查看球场' },
    intro: {
      eyebrow: '真正拉开差距的地方',
      title: '马略卡很多高尔夫体验，都是从预订平台开始，以一张账单结束。这里更像一场真正为你安排好的私人一天。',
      body: '我会在岛上最好的球场陪你打一整天，指导直接发生在球场上，而不是打完以后再补几句建议。球会打得更好，决策会更清楚，整天的体验也会更周到。',
      stats: [
        { value: '18', label: '年高尔夫执教经验' },
        { value: '15,000+', label: '完成课程次数' },
        { value: '300+', label: '带出的冠军球员' },
      ],
    },
    socialProof: 'Andy 教练 · TikTok 高尔夫教学视频累计播放超过 3 亿次 · 教学内容受到全球球友关注',
    how: { eyebrow: '流程很简单', title: '三个步骤。', steps: [{ number: '01', title: '联系我', text: '告诉我你的日期、差点和你想要什么样的一天。我会在 24 小时内亲自回复。' }, { number: '02', title: '我来安排这一天', text: '球场建议、开球时间、午餐和交通都会在你到场前安排好。' }, { number: '03', title: '到场开打', text: '你唯一要做的，就是享受这一轮。大多数人都会比自己预想中打得更好。' }] },
    whyMallorca: { eyebrow: '为什么是马略卡', title: '马略卡有真正达到巡回赛水准的球场。很多来这里的人，其实只看到了很小的一部分。', paragraphs: ['欧洲很多顶级球场一到冬天就关门，马略卡不会。每年 10 月到次年 4 月，是这里的甜蜜期：果岭费更低，球场更安静，球况却依然出色。', '全岛共有 22 座球场，距离都不算远，其中不少有巡回赛历史，也有很成熟的设计。马略卡是真正的高尔夫目的地，只是大多数访客还没有真正认识它。'], stats: [{ value: '22', label: '岛上球场数量' }, { value: '300+', label: '年均晴天' }, { value: 'Jan-Dec', label: '全年可打' }, { value: '€80-220', label: '果岭费区间' }] },
    courses: { eyebrow: '精选球场', title: '马略卡最值得打的球场，我都亲自打过，也认真评过。', viewAll: '查看全部 22 座球场 →' },
    experience: {
      eyebrow: '这一天会是什么样',
      title: '马略卡大多数高尔夫体验，不过就是一个开球时间和一句再见。',
      paragraphs: ['我在中国执教了十多年，客户要的是实实在在的进步，不是空泛的鼓励。', '这段经历决定了我现在带每一轮球的方式。我们会一起打马略卡最好的球场，而指导会出现在真正影响成绩的地方。', '在你到场之前，一切都已经安排好：球场、开球时间和午餐。你那天唯一的任务，就是好好打球。'],
      button: '查看体验',
      features: [
        { title: '一切都已安排好', text: '球场、开球时间、交通和午餐都会在你到场前安排妥当。' },
        { title: '下场指导', text: '真正有用的观察会出现在一轮当中，而且是在还来得及改变结果的时候。' },
        { title: '完全私密', text: '只有你和一位 PGA Advanced Professional，不会有陌生人加入。' },
        { title: '更多独家资源', text: '包括大多数访客无法自行预订的会员制球场。' },
      ],
    },
    packages: {
      eyebrow: '体验与套餐',
      title: '三种方式度过这一天。',
      intro: '三种方案都是私人的，也都由我亲自带。区别只在于，你希望围绕高尔夫把这一天安排到什么程度。',
      items: [
        {
          tier: 'Mallorca 基础轮次',
          name: '和职业教练一起下场',
          features: [
            '根据你的水平和差点选择球场',
            '开球时间确认并全部安排妥当',
            '开球前说明与热身',
            '与 Andy 一起打满 18 洞',
            '整轮下场指导',
            '打完后的复盘，直接而清楚',
          ],
          price: '€350/人 + green fee',
          note: '果岭费需另外支付。通常每人 €80 到 €220，取决于球场和季节。',
          cta: '咨询',
        },
        {
          tier: 'Signature Day',
          name: '全程陪同的高尔夫日',
          featured: true,
          features: [
            '包含 Mallorca 基础轮次的全部内容',
            'Son Gual 或 Alcanada，岛上最好的两座球场',
            '在俱乐部餐厅慢慢吃一顿午餐',
            '精心准备的惊喜礼物',
            '节奏从容，真正完整的一天',
          ],
          price: '€450/人起 + green fee',
          note: '果岭费需另外支付。通常每人 €80 到 €220，取决于球场和季节。',
          cta: '咨询',
        },
        {
          tier: '完整体验',
          name: '定制高尔夫行程',
          features: [
            '多球场一天或完整 4 天行程',
            '从 Palma 酒店或别墅出发的私人接送',
            '安排精选餐厅晚餐',
            'Spa 或恢复疗程',
            'Tramuntana 山路日落兜风',
            '热气球飞越群山',
            '马略卡酒庄品酒',
            '为团体与企业提供 concierge 式统筹',
          ],
          price: '按需求定制',
          cta: '咨询',
        },
      ],
    },
    faq: {
      eyebrow: '常见问题',
      title: '大家联系我之前最常问的事。',
      intro: '告诉我你的日期、差点和你想要什么样的一天。我会在 24 小时内亲自回复。',
      items: [
        { q: '一定要打得很好吗？', a: '不需要。这个体验会根据你的水平来调整。无论是初学者还是低差点球员，都能从中得到真正的帮助。' },
        { q: '通常会安排在哪个球场？', a: '要看你本人。Son Gual 和 Alcanada 是我做完整高质量一天时最常用的两个球场，但并不是每次都最合适。' },
        { q: '怎么预订？', a: '直接联系我就行。把你的日期和想要的体验告诉我，我会在 24 小时内亲自回复。没有预订平台，也不用排队等。' },
        { q: '适合团体吗？', a: '适合。无论是一人、两人、朋友小团体，还是企业接待日，都可以安排。' },
        { q: '一年里什么时候最好？', a: '十月、十一月、三月和四月。球场状态、天气、性价比和节奏，这几个月的平衡最好。' },
      ],
    },
    finalCta: { eyebrow: '准备好真正打懂马略卡了吗？', title: '联系我，剩下的我来安排。', body: '告诉我你的日期、差点，以及你希望这一天达到什么效果。我会在 24 小时内亲自回复。', primaryCta: '预订这一天', secondaryCta: 'WhatsApp' },
  },
}

for (const [locale, override] of Object.entries(HOME_OVERRIDES)) {
  HOME_CONTENT[locale] = deepMerge(HOME_CONTENT.en, {
    locale,
    ...override,
  })
}

export function getHomeContent(locale = 'en') {
  return HOME_CONTENT[locale] || HOME_CONTENT.en
}
