"""
Weekly GA4 report runner for Mr Mallorca Golf.

Runs the existing GA4 report, saves a local text copy, and optionally emails it
through the existing Zoho Mail helper.
"""

import argparse
import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
REPORTS_DIR = ROOT / "ga4_analytics" / "reports"
DOWNLOADS_COPY = Path.home() / "Downloads" / "MMG Reports" / "MMG GA4 Weekly Latest.txt"


def run_report(days: int) -> str:
    result = subprocess.run(
        [sys.executable, str(ROOT / "ga4_analytics" / "ga4_report.py"), "--days", str(days), "--report", "all"],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    output = (result.stdout or "") + (result.stderr or "")
    if result.returncode != 0 and "ERROR" not in output:
        output += f"\nReport process exited with code {result.returncode}\n"
    return output


def save_report(output: str) -> Path:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    stamp = datetime.now().strftime("%Y-%m-%d")
    archive = REPORTS_DIR / f"ga4-weekly-{stamp}.txt"
    archive.write_text(output, encoding="utf-8")
    try:
      DOWNLOADS_COPY.parent.mkdir(parents=True, exist_ok=True)
      DOWNLOADS_COPY.write_text(output, encoding="utf-8")
    except OSError:
      pass
    return archive


def send_email(output: str, archive: Path) -> None:
    subject = f"MMG weekly GA4 report - {datetime.now():%Y-%m-%d}"
    body = (
        output
        + "\n\n---\n"
        + f"Saved locally: {archive}\n"
        + "Generated by C:\\Users\\andyg\\Desktop\\cursor\\mrmallorcagolf-real\\ga4_analytics\\weekly_ga4_email.py\n"
    )
    result = subprocess.run(
        [
            sys.executable,
            str(ROOT / "zoho_mail" / "zoho_mail.py"),
            "send",
            "--to",
            "andy@mrmallorcagolf.com",
            "--subject",
            subject,
            "--body",
            body,
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
    )
    print(result.stdout)
    if result.returncode != 0:
        print(result.stderr, file=sys.stderr)
        raise SystemExit(result.returncode)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--days", type=int, default=7)
    parser.add_argument("--send", action="store_true", help="Email the report through Zoho")
    args = parser.parse_args()

    output = run_report(args.days)
    archive = save_report(output)
    print(output)
    print(f"Saved: {archive}")
    if DOWNLOADS_COPY.exists():
        print(f"Latest copy: {DOWNLOADS_COPY}")

    if args.send:
        send_email(output, archive)


if __name__ == "__main__":
    main()
